// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module BoothEncoder(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7
  input  [15:0] io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
  output [7:0]  io_neg,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
                io_zero,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
                io_two	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
);

  assign io_neg =
    {io_b[15], io_b[13], io_b[11], io_b[9], io_b[7], io_b[5], io_b[3], io_b[1]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7, :56:25, :61:22
  assign io_zero =
    {io_b[15:13] == 3'h0 | (&(io_b[15:13])),
     io_b[13:11] == 3'h0 | (&(io_b[13:11])),
     io_b[11:9] == 3'h0 | (&(io_b[11:9])),
     io_b[9:7] == 3'h0 | (&(io_b[9:7])),
     io_b[7:5] == 3'h0 | (&(io_b[7:5])),
     io_b[5:3] == 3'h0 | (&(io_b[5:3])),
     io_b[3:1] == 3'h0 | (&(io_b[3:1])),
     io_b[1:0] == 2'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7, :39:24, :42:20, :57:{27,36,46}, :62:23
  assign io_two =
    {io_b[15:13] == 3'h3 | io_b[15:13] == 3'h4,
     io_b[13:11] == 3'h3 | io_b[13:11] == 3'h4,
     io_b[11:9] == 3'h3 | io_b[11:9] == 3'h4,
     io_b[9:7] == 3'h3 | io_b[9:7] == 3'h4,
     io_b[7:5] == 3'h3 | io_b[7:5] == 3'h4,
     io_b[5:3] == 3'h3 | io_b[5:3] == 3'h4,
     io_b[3:1] == 3'h3 | io_b[3:1] == 3'h4,
     io_b[1:0] == 2'h2};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7, :39:24, :42:20, :58:{27,36,46}, :63:22
endmodule

module PartialProductGen(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7
  input  [15:0] io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
  input  [7:0]  io_neg,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_zero,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_two,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
  output [32:0] io_pp_0,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_1,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_2,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_3,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_4,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_5,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_6,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_7	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
);

  wire [16:0] _GEN = {io_a, 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19
  wire [16:0] _GEN_0 = {io_a[15], io_a};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :104:21
  wire [16:0] _GEN_1 = io_two[0] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_0_aFinal =
    io_zero[0] ? 18'h0 : io_neg[0] ? 18'h0 - {io_a[15], _GEN_1} : {io_a[15], _GEN_1};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_2 = io_two[1] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_1_aFinal =
    io_zero[1] ? 18'h0 : io_neg[1] ? 18'h0 - {io_a[15], _GEN_2} : {io_a[15], _GEN_2};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_3 = io_two[2] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_2_aFinal =
    io_zero[2] ? 18'h0 : io_neg[2] ? 18'h0 - {io_a[15], _GEN_3} : {io_a[15], _GEN_3};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_4 = io_two[3] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_3_aFinal =
    io_zero[3] ? 18'h0 : io_neg[3] ? 18'h0 - {io_a[15], _GEN_4} : {io_a[15], _GEN_4};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_5 = io_two[4] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_4_aFinal =
    io_zero[4] ? 18'h0 : io_neg[4] ? 18'h0 - {io_a[15], _GEN_5} : {io_a[15], _GEN_5};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_6 = io_two[5] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_5_aFinal =
    io_zero[5] ? 18'h0 : io_neg[5] ? 18'h0 - {io_a[15], _GEN_6} : {io_a[15], _GEN_6};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_7 = io_two[6] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_6_aFinal =
    io_zero[6] ? 18'h0 : io_neg[6] ? 18'h0 - {io_a[15], _GEN_7} : {io_a[15], _GEN_7};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_8 = io_two[7] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_7_aFinal =
    io_zero[7] ? 18'h0 : io_neg[7] ? 18'h0 - {io_a[15], _GEN_8} : {io_a[15], _GEN_8};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  assign io_pp_0 = {{15{io_pp_0_aFinal[17]}}, io_pp_0_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_1 = {{15{io_pp_1_aFinal[17]}}, io_pp_1_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_2 = {{15{io_pp_2_aFinal[17]}}, io_pp_2_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_3 = {{15{io_pp_3_aFinal[17]}}, io_pp_3_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_4 = {{15{io_pp_4_aFinal[17]}}, io_pp_4_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_5 = {{15{io_pp_5_aFinal[17]}}, io_pp_5_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_6 = {{15{io_pp_6_aFinal[17]}}, io_pp_6_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_7 = {{15{io_pp_7_aFinal[17]}}, io_pp_7_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
endmodule

module Compressor4to2(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7
  input  io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_c,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_d,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_cin,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
  output io_sum,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_carry,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_cout	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
);

  wire w1 = io_a ^ io_b;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:45:17
  wire w3 = w1 ^ io_c ^ io_d;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:45:17, :47:15
  assign io_sum = w3 ^ io_cin;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7, :47:15, :53:16
  assign io_carry = w3 ? io_cin : io_d;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7, :47:15, :56:18
  assign io_cout = w1 ? io_c : io_a;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7, :45:17, :50:17
endmodule

module Compressor4to2Array(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:62:7
  input  [39:0] io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_c,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_d,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
  output [39:0] io_sum,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_carry	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
);

  wire _comp_39_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_39_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_38_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_38_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_38_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_37_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_37_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_37_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_36_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_36_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_36_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_35_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_35_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_35_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_34_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_34_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_34_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_33_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_33_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_33_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_32_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_32_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_32_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_31_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_31_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_31_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_30_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_30_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_30_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_29_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_29_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_29_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_28_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_28_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_28_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_27_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_27_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_27_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_26_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_26_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_26_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_25_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_25_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_25_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_24_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_24_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_24_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_23_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_23_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_23_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_22_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_22_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_22_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_21_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_21_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_21_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_20_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_20_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_20_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_19_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_19_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_19_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_18_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_18_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_18_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_17_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_17_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_17_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_16_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_16_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_16_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_15_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_15_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_15_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_14_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_14_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_14_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_13_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_13_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_13_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_12_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_12_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_12_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_11_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_11_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_11_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_10_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_10_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_10_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_9_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_9_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_9_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_8_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_8_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_8_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_7_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_7_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_7_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_6_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_6_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_6_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_5_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_5_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_5_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_4_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_4_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_4_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_3_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_3_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_3_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_2_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_2_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_2_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_1_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_1_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_1_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  Compressor4to2 comp (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (1'h0),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:76:16
    .io_sum   (_comp_io_sum),
    .io_carry (_comp_io_carry),
    .io_cout  (_comp_io_cout)
  );
  Compressor4to2 comp_1 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_1_io_sum),
    .io_carry (_comp_1_io_carry),
    .io_cout  (_comp_1_io_cout)
  );
  Compressor4to2 comp_2 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_1_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_2_io_sum),
    .io_carry (_comp_2_io_carry),
    .io_cout  (_comp_2_io_cout)
  );
  Compressor4to2 comp_3 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_2_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_3_io_sum),
    .io_carry (_comp_3_io_carry),
    .io_cout  (_comp_3_io_cout)
  );
  Compressor4to2 comp_4 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_3_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_4_io_sum),
    .io_carry (_comp_4_io_carry),
    .io_cout  (_comp_4_io_cout)
  );
  Compressor4to2 comp_5 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_4_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_5_io_sum),
    .io_carry (_comp_5_io_carry),
    .io_cout  (_comp_5_io_cout)
  );
  Compressor4to2 comp_6 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_5_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_6_io_sum),
    .io_carry (_comp_6_io_carry),
    .io_cout  (_comp_6_io_cout)
  );
  Compressor4to2 comp_7 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_6_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_7_io_sum),
    .io_carry (_comp_7_io_carry),
    .io_cout  (_comp_7_io_cout)
  );
  Compressor4to2 comp_8 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_7_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_8_io_sum),
    .io_carry (_comp_8_io_carry),
    .io_cout  (_comp_8_io_cout)
  );
  Compressor4to2 comp_9 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_8_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_9_io_sum),
    .io_carry (_comp_9_io_carry),
    .io_cout  (_comp_9_io_cout)
  );
  Compressor4to2 comp_10 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_9_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_10_io_sum),
    .io_carry (_comp_10_io_carry),
    .io_cout  (_comp_10_io_cout)
  );
  Compressor4to2 comp_11 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_10_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_11_io_sum),
    .io_carry (_comp_11_io_carry),
    .io_cout  (_comp_11_io_cout)
  );
  Compressor4to2 comp_12 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_11_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_12_io_sum),
    .io_carry (_comp_12_io_carry),
    .io_cout  (_comp_12_io_cout)
  );
  Compressor4to2 comp_13 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_12_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_13_io_sum),
    .io_carry (_comp_13_io_carry),
    .io_cout  (_comp_13_io_cout)
  );
  Compressor4to2 comp_14 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_13_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_14_io_sum),
    .io_carry (_comp_14_io_carry),
    .io_cout  (_comp_14_io_cout)
  );
  Compressor4to2 comp_15 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_14_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_15_io_sum),
    .io_carry (_comp_15_io_carry),
    .io_cout  (_comp_15_io_cout)
  );
  Compressor4to2 comp_16 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_15_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_16_io_sum),
    .io_carry (_comp_16_io_carry),
    .io_cout  (_comp_16_io_cout)
  );
  Compressor4to2 comp_17 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_16_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_17_io_sum),
    .io_carry (_comp_17_io_carry),
    .io_cout  (_comp_17_io_cout)
  );
  Compressor4to2 comp_18 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_17_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_18_io_sum),
    .io_carry (_comp_18_io_carry),
    .io_cout  (_comp_18_io_cout)
  );
  Compressor4to2 comp_19 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_18_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_19_io_sum),
    .io_carry (_comp_19_io_carry),
    .io_cout  (_comp_19_io_cout)
  );
  Compressor4to2 comp_20 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_19_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_20_io_sum),
    .io_carry (_comp_20_io_carry),
    .io_cout  (_comp_20_io_cout)
  );
  Compressor4to2 comp_21 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_20_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_21_io_sum),
    .io_carry (_comp_21_io_carry),
    .io_cout  (_comp_21_io_cout)
  );
  Compressor4to2 comp_22 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_21_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_22_io_sum),
    .io_carry (_comp_22_io_carry),
    .io_cout  (_comp_22_io_cout)
  );
  Compressor4to2 comp_23 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_22_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_23_io_sum),
    .io_carry (_comp_23_io_carry),
    .io_cout  (_comp_23_io_cout)
  );
  Compressor4to2 comp_24 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_23_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_24_io_sum),
    .io_carry (_comp_24_io_carry),
    .io_cout  (_comp_24_io_cout)
  );
  Compressor4to2 comp_25 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_24_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_25_io_sum),
    .io_carry (_comp_25_io_carry),
    .io_cout  (_comp_25_io_cout)
  );
  Compressor4to2 comp_26 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_25_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_26_io_sum),
    .io_carry (_comp_26_io_carry),
    .io_cout  (_comp_26_io_cout)
  );
  Compressor4to2 comp_27 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_26_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_27_io_sum),
    .io_carry (_comp_27_io_carry),
    .io_cout  (_comp_27_io_cout)
  );
  Compressor4to2 comp_28 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_27_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_28_io_sum),
    .io_carry (_comp_28_io_carry),
    .io_cout  (_comp_28_io_cout)
  );
  Compressor4to2 comp_29 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_28_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_29_io_sum),
    .io_carry (_comp_29_io_carry),
    .io_cout  (_comp_29_io_cout)
  );
  Compressor4to2 comp_30 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_29_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_30_io_sum),
    .io_carry (_comp_30_io_carry),
    .io_cout  (_comp_30_io_cout)
  );
  Compressor4to2 comp_31 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_30_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_31_io_sum),
    .io_carry (_comp_31_io_carry),
    .io_cout  (_comp_31_io_cout)
  );
  Compressor4to2 comp_32 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_31_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_32_io_sum),
    .io_carry (_comp_32_io_carry),
    .io_cout  (_comp_32_io_cout)
  );
  Compressor4to2 comp_33 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_32_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_33_io_sum),
    .io_carry (_comp_33_io_carry),
    .io_cout  (_comp_33_io_cout)
  );
  Compressor4to2 comp_34 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_33_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_34_io_sum),
    .io_carry (_comp_34_io_carry),
    .io_cout  (_comp_34_io_cout)
  );
  Compressor4to2 comp_35 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_34_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_35_io_sum),
    .io_carry (_comp_35_io_carry),
    .io_cout  (_comp_35_io_cout)
  );
  Compressor4to2 comp_36 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_35_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_36_io_sum),
    .io_carry (_comp_36_io_carry),
    .io_cout  (_comp_36_io_cout)
  );
  Compressor4to2 comp_37 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_36_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_37_io_sum),
    .io_carry (_comp_37_io_carry),
    .io_cout  (_comp_37_io_cout)
  );
  Compressor4to2 comp_38 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_37_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_38_io_sum),
    .io_carry (_comp_38_io_carry),
    .io_cout  (_comp_38_io_cout)
  );
  Compressor4to2 comp_39 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_38_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_39_io_sum),
    .io_carry (_comp_39_io_carry),
    .io_cout  (/* unused */)
  );
  assign io_sum =
    {_comp_39_io_sum,
     _comp_38_io_sum,
     _comp_37_io_sum,
     _comp_36_io_sum,
     _comp_35_io_sum,
     _comp_34_io_sum,
     _comp_33_io_sum,
     _comp_32_io_sum,
     _comp_31_io_sum,
     _comp_30_io_sum,
     _comp_29_io_sum,
     _comp_28_io_sum,
     _comp_27_io_sum,
     _comp_26_io_sum,
     _comp_25_io_sum,
     _comp_24_io_sum,
     _comp_23_io_sum,
     _comp_22_io_sum,
     _comp_21_io_sum,
     _comp_20_io_sum,
     _comp_19_io_sum,
     _comp_18_io_sum,
     _comp_17_io_sum,
     _comp_16_io_sum,
     _comp_15_io_sum,
     _comp_14_io_sum,
     _comp_13_io_sum,
     _comp_12_io_sum,
     _comp_11_io_sum,
     _comp_10_io_sum,
     _comp_9_io_sum,
     _comp_8_io_sum,
     _comp_7_io_sum,
     _comp_6_io_sum,
     _comp_5_io_sum,
     _comp_4_io_sum,
     _comp_3_io_sum,
     _comp_2_io_sum,
     _comp_1_io_sum,
     _comp_io_sum};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:62:7, :79:22, :91:23
  assign io_carry =
    {_comp_39_io_carry,
     _comp_38_io_carry,
     _comp_37_io_carry,
     _comp_36_io_carry,
     _comp_35_io_carry,
     _comp_34_io_carry,
     _comp_33_io_carry,
     _comp_32_io_carry,
     _comp_31_io_carry,
     _comp_30_io_carry,
     _comp_29_io_carry,
     _comp_28_io_carry,
     _comp_27_io_carry,
     _comp_26_io_carry,
     _comp_25_io_carry,
     _comp_24_io_carry,
     _comp_23_io_carry,
     _comp_22_io_carry,
     _comp_21_io_carry,
     _comp_20_io_carry,
     _comp_19_io_carry,
     _comp_18_io_carry,
     _comp_17_io_carry,
     _comp_16_io_carry,
     _comp_15_io_carry,
     _comp_14_io_carry,
     _comp_13_io_carry,
     _comp_12_io_carry,
     _comp_11_io_carry,
     _comp_10_io_carry,
     _comp_9_io_carry,
     _comp_8_io_carry,
     _comp_7_io_carry,
     _comp_6_io_carry,
     _comp_5_io_carry,
     _comp_4_io_carry,
     _comp_3_io_carry,
     _comp_2_io_carry,
     _comp_1_io_carry,
     _comp_io_carry};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:62:7, :79:22, :92:25
endmodule

module Mult16Booth(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
  input         clock,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
                reset,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
  input  [15:0] io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:16:14
                io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:16:14
  input         io_validIn,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:16:14
  output [31:0] io_product,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:16:14
  output        io_validOut	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:16:14
);

  wire [39:0] _comp42_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:97:22
  wire [39:0] _comp42_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:97:22
  wire [32:0] _ppGen_io_pp_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [32:0] _ppGen_io_pp_1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [32:0] _ppGen_io_pp_2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [32:0] _ppGen_io_pp_3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [32:0] _ppGen_io_pp_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [32:0] _ppGen_io_pp_5;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [32:0] _ppGen_io_pp_6;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [32:0] _ppGen_io_pp_7;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
  wire [7:0]  _booth_io_neg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:29:21
  wire [7:0]  _booth_io_zero;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:29:21
  wire [7:0]  _booth_io_two;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:29:21
  reg  [7:0]  negS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24
  reg  [7:0]  zeroS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:34:24
  reg  [7:0]  twoS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:35:24
  reg  [15:0] aS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:36:24
  reg         validS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24
  reg  [39:0] row0S2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25
  reg  [39:0] row1S2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:81:25
  reg  [39:0] row2S2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:82:25
  reg  [39:0] row3S2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:83:25
  reg         validS2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:84:25
  reg  [31:0] productS3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:107:26
  reg         validS3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:108:26
  always @(posedge clock or posedge reset) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
    if (reset) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
      negS1 <= 8'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24
      zeroS1 <= 8'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24, :34:24
      twoS1 <= 8'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24, :35:24
      aS1 <= 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:36:24
      validS1 <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24
      row0S2 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25
      row1S2 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25, :81:25
      row2S2 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25, :82:25
      row3S2 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25, :83:25
      validS2 <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :84:25
      productS3 <= 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:107:26
      validS3 <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :108:26
    end
    else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
      automatic logic [39:0] csa1Sum =
        {{7{_ppGen_io_pp_0[32]}}, _ppGen_io_pp_0}
        ^ {{5{_ppGen_io_pp_1[32]}}, _ppGen_io_pp_1, 2'h0}
        ^ {{3{_ppGen_io_pp_2[32]}}, _ppGen_io_pp_2, 4'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :46:21, :61:{22,27,45}, :62:{22,27,45}, :63:{22,27,45}
      automatic logic [38:0] _GEN = {{6{_ppGen_io_pp_0[32]}}, _ppGen_io_pp_0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21, :61:{22,45}
      automatic logic [38:0] _GEN_0 = {{4{_ppGen_io_pp_1[32]}}, _ppGen_io_pp_1, 2'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21, :62:{22,45}
      automatic logic [38:0] _GEN_1 = {{2{_ppGen_io_pp_2[32]}}, _ppGen_io_pp_2, 4'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :46:21, :63:{22,45}
      automatic logic [38:0] csa1Carry = _GEN & _GEN_0 | _GEN_0 & _GEN_1 | _GEN & _GEN_1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:61:22, :62:22, :63:22
      automatic logic [39:0] csa2Sum =
        {_ppGen_io_pp_3[32], _ppGen_io_pp_3, 6'h0} ^ {1'h0, _ppGen_io_pp_4[30:0], 8'h0}
        ^ {1'h0, _ppGen_io_pp_5[28:0], 10'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24, :37:24, :46:21, :64:{22,37}, :65:{16,37}, :66:{16,22,37}
      automatic logic [38:0] _GEN_2 = {_ppGen_io_pp_3, 6'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21, :64:22
      automatic logic [38:0] _GEN_3 = {_ppGen_io_pp_4[30:0], 8'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24, :46:21, :65:{16,37}
      automatic logic [38:0] _GEN_4 = {_ppGen_io_pp_5[28:0], 10'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21, :66:{16,22,37}
      automatic logic [38:0] csa2Carry =
        _GEN_2 & _GEN_3 | _GEN_3 & _GEN_4 | _GEN_2 & _GEN_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:64:22, :65:16, :66:16
      automatic logic [38:0] _GEN_5 = {csa1Carry[37:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :76:50
      automatic logic [38:0] _GEN_6 = {_ppGen_io_pp_6[26:0], 12'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21, :67:{16,22,37}
      automatic logic [38:0] _GEN_7 = {csa2Carry[37:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :77:50
      automatic logic [38:0] _GEN_8 = {_ppGen_io_pp_7[24:0], 14'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21, :68:{16,22,37}
      negS1 <= _booth_io_neg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:29:21, :33:24
      zeroS1 <= _booth_io_zero;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:29:21, :34:24
      twoS1 <= _booth_io_two;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:29:21, :35:24
      aS1 <= io_a;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:36:24
      validS1 <= io_validIn;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24
      row0S2 <= csa1Sum ^ {csa1Carry, 1'h0} ^ {1'h0, _ppGen_io_pp_6[26:0], 12'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :46:21, :67:{16,22,37}, :76:50, :80:25
      row1S2 <= {csa1Sum[38:0] & _GEN_5 | _GEN_5 & _GEN_6 | csa1Sum[38:0] & _GEN_6, 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :67:16, :76:50, :81:25, :87:17
      row2S2 <= csa2Sum ^ {csa2Carry, 1'h0} ^ {1'h0, _ppGen_io_pp_7[24:0], 14'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :46:21, :68:{16,22,37}, :77:50, :82:25
      row3S2 <= {csa2Sum[38:0] & _GEN_7 | _GEN_7 & _GEN_8 | csa2Sum[38:0] & _GEN_8, 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :68:16, :77:50, :83:25, :89:17
      validS2 <= validS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :84:25
      productS3 <= _comp42_io_sum[31:0] + {_comp42_io_carry[30:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :97:22, :104:36, :107:26
      validS3 <= validS2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:84:25, :108:26
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
      automatic logic [31:0] _RANDOM[0:7];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
        `INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
        end	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
        negS1 = _RANDOM[3'h0][7:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :33:24
        zeroS1 = _RANDOM[3'h0][15:8];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :33:24, :34:24
        twoS1 = _RANDOM[3'h0][23:16];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :33:24, :35:24
        aS1 = {_RANDOM[3'h0][31:24], _RANDOM[3'h1][7:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :33:24, :36:24
        validS1 = _RANDOM[3'h1][8];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :36:24, :37:24
        row0S2 = {_RANDOM[3'h1][31:9], _RANDOM[3'h2][16:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :36:24, :80:25
        row1S2 = {_RANDOM[3'h2][31:17], _RANDOM[3'h3][24:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :80:25, :81:25
        row2S2 = {_RANDOM[3'h3][31:25], _RANDOM[3'h4], _RANDOM[3'h5][0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :81:25, :82:25
        row3S2 = {_RANDOM[3'h5][31:1], _RANDOM[3'h6][8:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :82:25, :83:25
        validS2 = _RANDOM[3'h6][9];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :83:25, :84:25
        productS3 = {_RANDOM[3'h6][31:10], _RANDOM[3'h7][9:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :83:25, :107:26
        validS3 = _RANDOM[3'h7][10];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :107:26, :108:26
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
        negS1 = 8'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24
        zeroS1 = 8'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24, :34:24
        twoS1 = 8'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24, :35:24
        aS1 = 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:36:24
        validS1 = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24
        row0S2 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25
        row1S2 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25, :81:25
        row2S2 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25, :82:25
        row3S2 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25, :83:25
        validS2 = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :84:25
        productS3 = 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:107:26
        validS3 = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:37:24, :108:26
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
      `FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  BoothEncoder booth (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:29:21
    .io_b    (io_b),
    .io_neg  (_booth_io_neg),
    .io_zero (_booth_io_zero),
    .io_two  (_booth_io_two)
  );
  PartialProductGen ppGen (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:46:21
    .io_a    (aS1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:36:24
    .io_neg  (negS1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:33:24
    .io_zero (zeroS1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:34:24
    .io_two  (twoS1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:35:24
    .io_pp_0 (_ppGen_io_pp_0),
    .io_pp_1 (_ppGen_io_pp_1),
    .io_pp_2 (_ppGen_io_pp_2),
    .io_pp_3 (_ppGen_io_pp_3),
    .io_pp_4 (_ppGen_io_pp_4),
    .io_pp_5 (_ppGen_io_pp_5),
    .io_pp_6 (_ppGen_io_pp_6),
    .io_pp_7 (_ppGen_io_pp_7)
  );
  Compressor4to2Array comp42 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:97:22
    .io_a     (row0S2),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:80:25
    .io_b     (row1S2),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:81:25
    .io_c     (row2S2),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:82:25
    .io_d     (row3S2),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:83:25
    .io_sum   (_comp42_io_sum),
    .io_carry (_comp42_io_carry)
  );
  assign io_product = productS3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :107:26
  assign io_validOut = validS3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth.scala:15:7, :108:26
endmodule

module mac16(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
  input  clk,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21
         rst_n,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:11:21
         mode,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:12:21
         inA,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:13:21
         inB,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:14:21
  output sum_out,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:15:21
         carry,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:16:21
         out_ready	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:17:21
);

  wire [31:0] _mult_io_product;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:54:22
  wire        _mult_io_validOut;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:54:22
  wire        _GEN = ~rst_n;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27
  reg  [2:0]  state;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24
  reg  [4:0]  cnt;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24
  reg  [15:0] shiftA;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25
  reg  [15:0] shiftB;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25
  reg  [23:0] accum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25
  reg  [23:0] prevProduct;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30
  reg  [23:0] outShiftReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:40:30
  reg         carryReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:42:27
  reg         firstOp;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:43:27
  reg         modeR;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:44:27
  reg         multValidIn;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31
  reg  [31:0] multReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:47:31
  wire        _multEnable_T_1 = cnt == 5'hF;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24, :50:47
  wire        multEnable = ~(|state) & _multEnable_T_1 | (|state) & ~(state[2]);	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :50:{29,40,47,70}, :51:{14,29,38}
  wire [24:0] addResult =
    modeR
      ? {1'h0, multReg[23:0]} + {1'h0, accum}
      : {1'h0, multReg[23:0]} + {1'h0, prevProduct};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :38:25, :39:30, :44:27, :47:31, :62:29, :63:{17,41,50}, :65:{17,41,50}
  wire        _GEN_0 = firstOp & ~modeR;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:43:27, :44:27, :62:16, :68:18
  wire [23:0] macResult = _GEN_0 ? multReg[23:0] : addResult[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:47:31, :62:29, :63:17, :65:17, :68:{18,42}, :69:{17,27}, :71:{17,29}
  wire        _GEN_1 = state == 3'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :78:19
  wire        _GEN_2 = state == 3'h2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :78:19
  wire        _GEN_3 = state == 3'h3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :78:19
  wire        _GEN_4 = state == 3'h4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :78:19
  wire        _GEN_5 = ~(|state) | _GEN_1 | _GEN_2 | _GEN_3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :39:30, :50:29, :78:19
  wire        _GEN_6 = state == 3'h5;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :78:19
  always @(posedge clk or posedge _GEN) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21, :21:27
    if (_GEN) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21, :21:27
      state <= 3'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
      cnt <= 5'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24
      shiftA <= 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25
      shiftB <= 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :37:25
      accum <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25
      prevProduct <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25, :39:30
      outShiftReg <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25, :40:30
      carryReg <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :42:27
      firstOp <= 1'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:43:27
      modeR <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :44:27
      multValidIn <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :46:31
      multReg <= 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:47:31
    end
    else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21
      if (|state) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :50:29
        automatic logic _GEN_7;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:136:18
        automatic logic _GEN_8;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :78:19, :136:42, :138:18
        automatic logic _GEN_9 = _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :78:19
        _GEN_7 = cnt == 5'h16;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24, :136:18
        _GEN_8 = _GEN_6 & _GEN_7;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :78:19, :136:{18,42}, :138:18
        if (_GEN_1)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:19
          state <= 3'h2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
        else if (_GEN_2)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:19
          state <= 3'h3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
        else if (_GEN_3) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:19
          if (_mult_io_validOut)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:54:22
            state <= 3'h4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
        end
        else if (_GEN_4)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:19
          state <= 3'h5;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
        else if (_GEN_8)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :78:19, :136:42, :138:18
          state <= 3'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
        if (_GEN_9 | ~_GEN_6) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24, :36:25, :78:19
        end
        else if (_GEN_7)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:136:18
          cnt <= 5'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24
        else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:136:18
          cnt <= cnt + 5'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24, :93:22, :142:22
        if (_GEN_9 | ~_GEN_8) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :36:25, :37:25, :78:19, :136:42, :138:18
        end
        else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :78:19
          shiftA <= 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25
          shiftB <= 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :37:25
        end
        multValidIn <= ~_GEN_1 & multValidIn;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31, :78:19, :98:21
      end
      else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:50:29
        if (_multEnable_T_1) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:50:47
          state <= 3'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
          cnt <= 5'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24
        end
        else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:50:47
          cnt <= cnt + 5'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24, :93:22
        shiftA <= {shiftA[14:0], inA};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :85:{22,29}
        shiftB <= {shiftB[14:0], inB};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :86:{22,29}
        modeR <= mode;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:44:27
        multValidIn <= _multEnable_T_1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31, :50:47
      end
      if (_GEN_5 | ~(_GEN_4 & modeR)) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25, :39:30, :44:27, :78:19, :116:33
      end
      else if (_GEN_0)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:68:18
        accum <= multReg[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25, :47:31, :69:27
      else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:68:18
        accum <= addResult[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25, :62:29, :63:17, :65:17, :71:29
      if (_GEN_5 | ~(_GEN_4 & ~modeR)) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :44:27, :62:16, :78:19, :116:33, :117:23
      end
      else if (_GEN_0)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:68:18
        prevProduct <= multReg[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :47:31, :69:27
      else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:68:18
        prevProduct <= addResult[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :62:29, :63:17, :65:17, :71:29
      if (~_GEN_5) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :42:27, :78:19
        if (_GEN_4)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:19
          outShiftReg <= macResult;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:40:30, :68:42, :69:17, :71:17
        else if (_GEN_6)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:19
          outShiftReg <= {outShiftReg[22:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :40:30, :133:{27,39}
      end
      carryReg <= ~_GEN_5 & _GEN_4 & (~firstOp | modeR) & addResult[24] | carryReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :42:27, :43:27, :44:27, :62:29, :63:17, :65:17, :78:19, :122:{15,24,46}
      firstOp <= (_GEN_5 | ~_GEN_4) & firstOp;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :43:27, :78:19, :126:18
      if (~(|state) | _GEN_1 | _GEN_2 | ~(_GEN_3 & _mult_io_validOut)) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :47:31, :50:29, :54:22, :78:19, :107:32, :108:19
      end
      else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:47:31, :78:19
        multReg <= _mult_io_product;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:47:31, :54:22
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
    `ifdef FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      automatic logic [31:0] _RANDOM[0:4];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `ifdef INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        `INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        end	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        state = _RANDOM[3'h0][2:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
        cnt = _RANDOM[3'h0][7:3];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :34:24
        shiftA = _RANDOM[3'h0][23:8];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :36:25
        shiftB = {_RANDOM[3'h0][31:24], _RANDOM[3'h1][7:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24, :37:25
        accum = _RANDOM[3'h1][31:8];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :37:25, :38:25
        prevProduct = _RANDOM[3'h2][23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30
        outShiftReg = {_RANDOM[3'h2][31:24], _RANDOM[3'h3][15:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :40:30
        carryReg = _RANDOM[3'h3][16];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :40:30, :42:27
        firstOp = _RANDOM[3'h3][17];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :40:30, :43:27
        modeR = _RANDOM[3'h3][18];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :40:30, :44:27
        multValidIn = _RANDOM[3'h3][19];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :40:30, :46:31
        multReg = {_RANDOM[3'h3][31:20], _RANDOM[3'h4][19:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :40:30, :47:31
      `endif // RANDOMIZE_REG_INIT
      if (_GEN) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :21:27
        state = 3'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :33:24
        cnt = 5'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:34:24
        shiftA = 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25
        shiftB = 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :37:25
        accum = 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25
        prevProduct = 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25, :39:30
        outShiftReg = 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:25, :40:30
        carryReg = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :42:27
        firstOp = 1'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:43:27
        modeR = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :44:27
        multValidIn = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :46:31
        multReg = 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:47:31
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Mult16Booth mult (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:54:22
    .clock       (clk),
    .reset       (_GEN),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27
    .io_a        (multEnable ? shiftA : 16'h0),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :50:70, :55:27
    .io_b        (multEnable ? shiftB : 16'h0),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :37:25, :50:70, :56:27
    .io_validIn  (multValidIn),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31
    .io_product  (_mult_io_product),
    .io_validOut (_mult_io_validOut)
  );
  assign sum_out = ~_GEN_5 & (_GEN_4 ? macResult[23] : _GEN_6 & outShiftReg[22]);	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :40:30, :42:27, :68:42, :69:17, :71:17, :75:15, :78:19, :81:19, :128:{19,31}, :134:{19,33}
  assign carry = carryReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :42:27
  assign out_ready = ~_GEN_5 & _GEN_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :42:27, :76:15, :78:19, :80:19
endmodule

