// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module BoothEncoder(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7
  input  [15:0] io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
  output [7:0]  io_neg,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
                io_zero,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
                io_two	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:14:14
);

  assign io_neg =
    {io_b[15], io_b[13], io_b[11], io_b[9], io_b[7], io_b[5], io_b[3], io_b[1]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7, :56:25, :61:22
  assign io_zero =
    {io_b[15:13] == 3'h0 | (&(io_b[15:13])),
     io_b[13:11] == 3'h0 | (&(io_b[13:11])),
     io_b[11:9] == 3'h0 | (&(io_b[11:9])),
     io_b[9:7] == 3'h0 | (&(io_b[9:7])),
     io_b[7:5] == 3'h0 | (&(io_b[7:5])),
     io_b[5:3] == 3'h0 | (&(io_b[5:3])),
     io_b[3:1] == 3'h0 | (&(io_b[3:1])),
     io_b[1:0] == 2'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7, :39:24, :42:20, :57:{27,36,46}, :62:23
  assign io_two =
    {io_b[15:13] == 3'h3 | io_b[15:13] == 3'h4,
     io_b[13:11] == 3'h3 | io_b[13:11] == 3'h4,
     io_b[11:9] == 3'h3 | io_b[11:9] == 3'h4,
     io_b[9:7] == 3'h3 | io_b[9:7] == 3'h4,
     io_b[7:5] == 3'h3 | io_b[7:5] == 3'h4,
     io_b[5:3] == 3'h3 | io_b[5:3] == 3'h4,
     io_b[3:1] == 3'h3 | io_b[3:1] == 3'h4,
     io_b[1:0] == 2'h2};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:13:7, :39:24, :42:20, :58:{27,36,46}, :63:22
endmodule

module PartialProductGen(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7
  input  [15:0] io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
  input  [7:0]  io_neg,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_zero,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_two,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
  output [32:0] io_pp_0,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_1,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_2,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_3,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_4,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_5,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_6,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
                io_pp_7	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:75:14
);

  wire [16:0] _GEN = {io_a, 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19
  wire [16:0] _GEN_0 = {io_a[15], io_a};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :104:21
  wire [16:0] _GEN_1 = io_two[0] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_0_aFinal =
    io_zero[0] ? 18'h0 : io_neg[0] ? 18'h0 - {io_a[15], _GEN_1} : {io_a[15], _GEN_1};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_2 = io_two[1] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_1_aFinal =
    io_zero[1] ? 18'h0 : io_neg[1] ? 18'h0 - {io_a[15], _GEN_2} : {io_a[15], _GEN_2};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_3 = io_two[2] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_2_aFinal =
    io_zero[2] ? 18'h0 : io_neg[2] ? 18'h0 - {io_a[15], _GEN_3} : {io_a[15], _GEN_3};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_4 = io_two[3] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_3_aFinal =
    io_zero[3] ? 18'h0 : io_neg[3] ? 18'h0 - {io_a[15], _GEN_4} : {io_a[15], _GEN_4};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_5 = io_two[4] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_4_aFinal =
    io_zero[4] ? 18'h0 : io_neg[4] ? 18'h0 - {io_a[15], _GEN_5} : {io_a[15], _GEN_5};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_6 = io_two[5] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_5_aFinal =
    io_zero[5] ? 18'h0 : io_neg[5] ? 18'h0 - {io_a[15], _GEN_6} : {io_a[15], _GEN_6};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_7 = io_two[6] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_6_aFinal =
    io_zero[6] ? 18'h0 : io_neg[6] ? 18'h0 - {io_a[15], _GEN_7} : {io_a[15], _GEN_7};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  wire [16:0] _GEN_8 = io_two[7] ? _GEN : _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:95:19, :100:25, :104:21, :105:19
  wire [17:0] io_pp_7_aFinal =
    io_zero[7] ? 18'h0 : io_neg[7] ? 18'h0 - {io_a[15], _GEN_8} : {io_a[15], _GEN_8};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:93:21, :98:25, :99:26, :105:19, :109:{19,29}, :112:21
  assign io_pp_0 = {{15{io_pp_0_aFinal[17]}}, io_pp_0_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_1 = {{15{io_pp_1_aFinal[17]}}, io_pp_1_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_2 = {{15{io_pp_2_aFinal[17]}}, io_pp_2_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_3 = {{15{io_pp_3_aFinal[17]}}, io_pp_3_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_4 = {{15{io_pp_4_aFinal[17]}}, io_pp_4_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_5 = {{15{io_pp_5_aFinal[17]}}, io_pp_5_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_6 = {{15{io_pp_6_aFinal[17]}}, io_pp_6_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
  assign io_pp_7 = {{15{io_pp_7_aFinal[17]}}, io_pp_7_aFinal};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/BoothEncoder.scala:74:7, :112:21, :115:{8,13,24}
endmodule

module Compressor4to2(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7
  input  io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_c,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_d,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_cin,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
  output io_sum,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_carry,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
         io_cout	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:34:14
);

  wire w1 = io_a ^ io_b;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:45:17
  wire w3 = w1 ^ io_c ^ io_d;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:45:17, :47:15
  assign io_sum = w3 ^ io_cin;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7, :47:15, :53:16
  assign io_carry = w3 ? io_cin : io_d;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7, :47:15, :56:18
  assign io_cout = w1 ? io_c : io_a;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:33:7, :45:17, :50:17
endmodule

module Compressor4to2Array(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:62:7
  input  [39:0] io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_c,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_d,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
  output [39:0] io_sum,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
                io_carry	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:63:14
);

  wire _comp_39_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_39_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_38_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_38_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_38_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_37_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_37_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_37_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_36_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_36_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_36_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_35_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_35_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_35_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_34_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_34_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_34_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_33_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_33_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_33_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_32_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_32_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_32_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_31_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_31_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_31_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_30_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_30_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_30_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_29_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_29_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_29_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_28_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_28_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_28_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_27_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_27_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_27_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_26_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_26_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_26_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_25_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_25_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_25_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_24_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_24_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_24_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_23_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_23_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_23_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_22_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_22_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_22_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_21_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_21_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_21_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_20_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_20_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_20_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_19_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_19_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_19_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_18_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_18_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_18_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_17_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_17_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_17_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_16_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_16_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_16_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_15_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_15_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_15_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_14_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_14_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_14_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_13_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_13_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_13_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_12_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_12_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_12_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_11_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_11_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_11_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_10_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_10_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_10_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_9_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_9_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_9_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_8_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_8_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_8_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_7_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_7_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_7_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_6_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_6_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_6_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_5_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_5_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_5_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_4_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_4_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_4_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_3_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_3_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_3_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_2_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_2_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_2_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_1_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_1_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_1_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  wire _comp_io_cout;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
  Compressor4to2 comp (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[0]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (1'h0),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:76:16
    .io_sum   (_comp_io_sum),
    .io_carry (_comp_io_carry),
    .io_cout  (_comp_io_cout)
  );
  Compressor4to2 comp_1 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[1]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_1_io_sum),
    .io_carry (_comp_1_io_carry),
    .io_cout  (_comp_1_io_cout)
  );
  Compressor4to2 comp_2 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[2]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_1_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_2_io_sum),
    .io_carry (_comp_2_io_carry),
    .io_cout  (_comp_2_io_cout)
  );
  Compressor4to2 comp_3 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[3]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_2_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_3_io_sum),
    .io_carry (_comp_3_io_carry),
    .io_cout  (_comp_3_io_cout)
  );
  Compressor4to2 comp_4 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[4]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_3_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_4_io_sum),
    .io_carry (_comp_4_io_carry),
    .io_cout  (_comp_4_io_cout)
  );
  Compressor4to2 comp_5 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[5]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_4_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_5_io_sum),
    .io_carry (_comp_5_io_carry),
    .io_cout  (_comp_5_io_cout)
  );
  Compressor4to2 comp_6 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[6]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_5_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_6_io_sum),
    .io_carry (_comp_6_io_carry),
    .io_cout  (_comp_6_io_cout)
  );
  Compressor4to2 comp_7 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[7]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_6_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_7_io_sum),
    .io_carry (_comp_7_io_carry),
    .io_cout  (_comp_7_io_cout)
  );
  Compressor4to2 comp_8 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[8]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_7_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_8_io_sum),
    .io_carry (_comp_8_io_carry),
    .io_cout  (_comp_8_io_cout)
  );
  Compressor4to2 comp_9 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[9]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_8_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_9_io_sum),
    .io_carry (_comp_9_io_carry),
    .io_cout  (_comp_9_io_cout)
  );
  Compressor4to2 comp_10 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[10]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_9_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_10_io_sum),
    .io_carry (_comp_10_io_carry),
    .io_cout  (_comp_10_io_cout)
  );
  Compressor4to2 comp_11 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[11]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_10_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_11_io_sum),
    .io_carry (_comp_11_io_carry),
    .io_cout  (_comp_11_io_cout)
  );
  Compressor4to2 comp_12 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[12]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_11_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_12_io_sum),
    .io_carry (_comp_12_io_carry),
    .io_cout  (_comp_12_io_cout)
  );
  Compressor4to2 comp_13 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[13]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_12_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_13_io_sum),
    .io_carry (_comp_13_io_carry),
    .io_cout  (_comp_13_io_cout)
  );
  Compressor4to2 comp_14 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[14]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_13_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_14_io_sum),
    .io_carry (_comp_14_io_carry),
    .io_cout  (_comp_14_io_cout)
  );
  Compressor4to2 comp_15 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[15]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_14_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_15_io_sum),
    .io_carry (_comp_15_io_carry),
    .io_cout  (_comp_15_io_cout)
  );
  Compressor4to2 comp_16 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[16]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_15_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_16_io_sum),
    .io_carry (_comp_16_io_carry),
    .io_cout  (_comp_16_io_cout)
  );
  Compressor4to2 comp_17 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[17]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_16_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_17_io_sum),
    .io_carry (_comp_17_io_carry),
    .io_cout  (_comp_17_io_cout)
  );
  Compressor4to2 comp_18 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[18]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_17_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_18_io_sum),
    .io_carry (_comp_18_io_carry),
    .io_cout  (_comp_18_io_cout)
  );
  Compressor4to2 comp_19 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[19]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_18_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_19_io_sum),
    .io_carry (_comp_19_io_carry),
    .io_cout  (_comp_19_io_cout)
  );
  Compressor4to2 comp_20 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[20]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_19_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_20_io_sum),
    .io_carry (_comp_20_io_carry),
    .io_cout  (_comp_20_io_cout)
  );
  Compressor4to2 comp_21 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[21]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_20_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_21_io_sum),
    .io_carry (_comp_21_io_carry),
    .io_cout  (_comp_21_io_cout)
  );
  Compressor4to2 comp_22 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[22]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_21_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_22_io_sum),
    .io_carry (_comp_22_io_carry),
    .io_cout  (_comp_22_io_cout)
  );
  Compressor4to2 comp_23 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[23]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_22_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_23_io_sum),
    .io_carry (_comp_23_io_carry),
    .io_cout  (_comp_23_io_cout)
  );
  Compressor4to2 comp_24 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[24]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_23_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_24_io_sum),
    .io_carry (_comp_24_io_carry),
    .io_cout  (_comp_24_io_cout)
  );
  Compressor4to2 comp_25 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[25]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_24_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_25_io_sum),
    .io_carry (_comp_25_io_carry),
    .io_cout  (_comp_25_io_cout)
  );
  Compressor4to2 comp_26 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[26]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_25_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_26_io_sum),
    .io_carry (_comp_26_io_carry),
    .io_cout  (_comp_26_io_cout)
  );
  Compressor4to2 comp_27 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[27]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_26_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_27_io_sum),
    .io_carry (_comp_27_io_carry),
    .io_cout  (_comp_27_io_cout)
  );
  Compressor4to2 comp_28 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[28]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_27_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_28_io_sum),
    .io_carry (_comp_28_io_carry),
    .io_cout  (_comp_28_io_cout)
  );
  Compressor4to2 comp_29 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[29]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_28_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_29_io_sum),
    .io_carry (_comp_29_io_carry),
    .io_cout  (_comp_29_io_cout)
  );
  Compressor4to2 comp_30 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[30]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_29_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_30_io_sum),
    .io_carry (_comp_30_io_carry),
    .io_cout  (_comp_30_io_cout)
  );
  Compressor4to2 comp_31 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[31]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_30_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_31_io_sum),
    .io_carry (_comp_31_io_carry),
    .io_cout  (_comp_31_io_cout)
  );
  Compressor4to2 comp_32 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[32]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_31_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_32_io_sum),
    .io_carry (_comp_32_io_carry),
    .io_cout  (_comp_32_io_cout)
  );
  Compressor4to2 comp_33 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[33]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_32_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_33_io_sum),
    .io_carry (_comp_33_io_carry),
    .io_cout  (_comp_33_io_cout)
  );
  Compressor4to2 comp_34 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[34]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_33_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_34_io_sum),
    .io_carry (_comp_34_io_carry),
    .io_cout  (_comp_34_io_cout)
  );
  Compressor4to2 comp_35 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[35]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_34_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_35_io_sum),
    .io_carry (_comp_35_io_carry),
    .io_cout  (_comp_35_io_cout)
  );
  Compressor4to2 comp_36 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[36]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_35_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_36_io_sum),
    .io_carry (_comp_36_io_carry),
    .io_cout  (_comp_36_io_cout)
  );
  Compressor4to2 comp_37 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[37]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_36_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_37_io_sum),
    .io_carry (_comp_37_io_carry),
    .io_cout  (_comp_37_io_cout)
  );
  Compressor4to2 comp_38 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[38]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_37_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_38_io_sum),
    .io_carry (_comp_38_io_carry),
    .io_cout  (_comp_38_io_cout)
  );
  Compressor4to2 comp_39 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_a     (io_a[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:80:24
    .io_b     (io_b[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:81:24
    .io_c     (io_c[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:82:24
    .io_d     (io_d[39]),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:83:24
    .io_cin   (_comp_38_io_cout),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:79:22
    .io_sum   (_comp_39_io_sum),
    .io_carry (_comp_39_io_carry),
    .io_cout  (/* unused */)
  );
  assign io_sum =
    {_comp_39_io_sum,
     _comp_38_io_sum,
     _comp_37_io_sum,
     _comp_36_io_sum,
     _comp_35_io_sum,
     _comp_34_io_sum,
     _comp_33_io_sum,
     _comp_32_io_sum,
     _comp_31_io_sum,
     _comp_30_io_sum,
     _comp_29_io_sum,
     _comp_28_io_sum,
     _comp_27_io_sum,
     _comp_26_io_sum,
     _comp_25_io_sum,
     _comp_24_io_sum,
     _comp_23_io_sum,
     _comp_22_io_sum,
     _comp_21_io_sum,
     _comp_20_io_sum,
     _comp_19_io_sum,
     _comp_18_io_sum,
     _comp_17_io_sum,
     _comp_16_io_sum,
     _comp_15_io_sum,
     _comp_14_io_sum,
     _comp_13_io_sum,
     _comp_12_io_sum,
     _comp_11_io_sum,
     _comp_10_io_sum,
     _comp_9_io_sum,
     _comp_8_io_sum,
     _comp_7_io_sum,
     _comp_6_io_sum,
     _comp_5_io_sum,
     _comp_4_io_sum,
     _comp_3_io_sum,
     _comp_2_io_sum,
     _comp_1_io_sum,
     _comp_io_sum};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:62:7, :79:22, :91:23
  assign io_carry =
    {_comp_39_io_carry,
     _comp_38_io_carry,
     _comp_37_io_carry,
     _comp_36_io_carry,
     _comp_35_io_carry,
     _comp_34_io_carry,
     _comp_33_io_carry,
     _comp_32_io_carry,
     _comp_31_io_carry,
     _comp_30_io_carry,
     _comp_29_io_carry,
     _comp_28_io_carry,
     _comp_27_io_carry,
     _comp_26_io_carry,
     _comp_25_io_carry,
     _comp_24_io_carry,
     _comp_23_io_carry,
     _comp_22_io_carry,
     _comp_21_io_carry,
     _comp_20_io_carry,
     _comp_19_io_carry,
     _comp_18_io_carry,
     _comp_17_io_carry,
     _comp_16_io_carry,
     _comp_15_io_carry,
     _comp_14_io_carry,
     _comp_13_io_carry,
     _comp_12_io_carry,
     _comp_11_io_carry,
     _comp_10_io_carry,
     _comp_9_io_carry,
     _comp_8_io_carry,
     _comp_7_io_carry,
     _comp_6_io_carry,
     _comp_5_io_carry,
     _comp_4_io_carry,
     _comp_3_io_carry,
     _comp_2_io_carry,
     _comp_1_io_carry,
     _comp_io_carry};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:62:7, :79:22, :92:25
endmodule

module Mult16Booth2Stage(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
  input         clock,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
                reset,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
  input  [15:0] io_a,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:16:14
                io_b,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:16:14
  input         io_validIn,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:16:14
  output [31:0] io_product,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:16:14
  output        io_validOut	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:16:14
);

  wire [39:0] _comp42_io_sum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:75:22
  wire [39:0] _comp42_io_carry;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:75:22
  wire [32:0] _ppGen_io_pp_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [32:0] _ppGen_io_pp_1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [32:0] _ppGen_io_pp_2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [32:0] _ppGen_io_pp_3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [32:0] _ppGen_io_pp_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [32:0] _ppGen_io_pp_5;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [32:0] _ppGen_io_pp_6;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [32:0] _ppGen_io_pp_7;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
  wire [7:0]  _booth_io_neg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:29:21
  wire [7:0]  _booth_io_zero;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:29:21
  wire [7:0]  _booth_io_two;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:29:21
  reg  [39:0] row0S1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25
  reg  [39:0] row1S1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:59:25
  reg  [39:0] row2S1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:60:25
  reg  [39:0] row3S1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:61:25
  reg         validS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:62:25
  reg  [31:0] productS2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:85:26
  reg         validS2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:86:26
  always @(posedge clock or posedge reset) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
    if (reset) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
      row0S1 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25
      row1S1 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25, :59:25
      row2S1 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25, :60:25
      row3S1 <= 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25, :61:25
      validS1 <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:54:50, :62:25
      productS2 <= 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:85:26
      validS2 <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:54:50, :86:26
    end
    else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
      automatic logic [39:0] csa1Sum =
        {{7{_ppGen_io_pp_0[32]}}, _ppGen_io_pp_0}
        ^ {{5{_ppGen_io_pp_1[32]}}, _ppGen_io_pp_1, 2'h0}
        ^ {{3{_ppGen_io_pp_2[32]}}, _ppGen_io_pp_2, 4'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :42:{22,27,45}, :43:{22,27,45}, :44:{22,27,45}
      automatic logic [38:0] _GEN = {{6{_ppGen_io_pp_0[32]}}, _ppGen_io_pp_0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :42:{22,45}
      automatic logic [38:0] _GEN_0 = {{4{_ppGen_io_pp_1[32]}}, _ppGen_io_pp_1, 2'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :43:{22,45}
      automatic logic [38:0] _GEN_1 = {{2{_ppGen_io_pp_2[32]}}, _ppGen_io_pp_2, 4'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :44:{22,45}
      automatic logic [38:0] csa1Carry = _GEN & _GEN_0 | _GEN_0 & _GEN_1 | _GEN & _GEN_1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:42:22, :43:22, :44:22
      automatic logic [39:0] csa2Sum =
        {_ppGen_io_pp_3[32], _ppGen_io_pp_3, 6'h0} ^ {1'h0, _ppGen_io_pp_4[30:0], 8'h0}
        ^ {1'h0, _ppGen_io_pp_5[28:0], 10'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :45:{22,37}, :46:{16,22,37}, :47:{16,22,37}, :54:50
      automatic logic [38:0] _GEN_2 = {_ppGen_io_pp_3, 6'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :45:22
      automatic logic [38:0] _GEN_3 = {_ppGen_io_pp_4[30:0], 8'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :46:{16,22,37}
      automatic logic [38:0] _GEN_4 = {_ppGen_io_pp_5[28:0], 10'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :47:{16,22,37}
      automatic logic [38:0] csa2Carry =
        _GEN_2 & _GEN_3 | _GEN_3 & _GEN_4 | _GEN_2 & _GEN_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:45:22, :46:16, :47:16
      automatic logic [38:0] _GEN_5 = {csa1Carry[37:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:54:50
      automatic logic [38:0] _GEN_6 = {_ppGen_io_pp_6[26:0], 12'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :48:{16,22,37}
      automatic logic [38:0] _GEN_7 = {csa2Carry[37:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:54:50, :55:50
      automatic logic [38:0] _GEN_8 = {_ppGen_io_pp_7[24:0], 14'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :49:{16,22,37}
      row0S1 <= csa1Sum ^ {csa1Carry, 1'h0} ^ {1'h0, _ppGen_io_pp_6[26:0], 12'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :48:{16,22,37}, :54:50, :58:25
      row1S1 <= {csa1Sum[38:0] & _GEN_5 | _GEN_5 & _GEN_6 | csa1Sum[38:0] & _GEN_6, 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:48:16, :54:50, :59:25, :65:17
      row2S1 <= csa2Sum ^ {csa2Carry, 1'h0} ^ {1'h0, _ppGen_io_pp_7[24:0], 14'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:35, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21, :49:{16,22,37}, :54:50, :55:50, :60:25
      row3S1 <= {csa2Sum[38:0] & _GEN_7 | _GEN_7 & _GEN_8 | csa2Sum[38:0] & _GEN_8, 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/common/Compressors.scala:24:23, :25:{20,30,35,40}, Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:49:16, :54:50, :55:50, :61:25, :67:17
      validS1 <= io_validIn;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:62:25
      productS2 <= _comp42_io_sum[31:0] + {_comp42_io_carry[30:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:54:50, :75:22, :82:36, :85:26
      validS2 <= validS1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:62:25, :86:26
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
      automatic logic [31:0] _RANDOM[0:6];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
        `INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
        end	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
        row0S1 = {_RANDOM[3'h0], _RANDOM[3'h1][7:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :58:25
        row1S1 = {_RANDOM[3'h1][31:8], _RANDOM[3'h2][15:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :58:25, :59:25
        row2S1 = {_RANDOM[3'h2][31:16], _RANDOM[3'h3][23:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :59:25, :60:25
        row3S1 = {_RANDOM[3'h3][31:24], _RANDOM[3'h4]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :60:25, :61:25
        validS1 = _RANDOM[3'h5][0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :62:25
        productS2 = {_RANDOM[3'h5][31:1], _RANDOM[3'h6][0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :62:25, :85:26
        validS2 = _RANDOM[3'h6][1];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :85:26, :86:26
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
        row0S1 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25
        row1S1 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25, :59:25
        row2S1 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25, :60:25
        row3S1 = 40'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25, :61:25
        validS1 = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:54:50, :62:25
        productS2 = 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:85:26
        validS2 = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:54:50, :86:26
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
      `FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  BoothEncoder booth (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:29:21
    .io_b    (io_b),
    .io_neg  (_booth_io_neg),
    .io_zero (_booth_io_zero),
    .io_two  (_booth_io_two)
  );
  PartialProductGen ppGen (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:33:21
    .io_a    (io_a),
    .io_neg  (_booth_io_neg),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:29:21
    .io_zero (_booth_io_zero),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:29:21
    .io_two  (_booth_io_two),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:29:21
    .io_pp_0 (_ppGen_io_pp_0),
    .io_pp_1 (_ppGen_io_pp_1),
    .io_pp_2 (_ppGen_io_pp_2),
    .io_pp_3 (_ppGen_io_pp_3),
    .io_pp_4 (_ppGen_io_pp_4),
    .io_pp_5 (_ppGen_io_pp_5),
    .io_pp_6 (_ppGen_io_pp_6),
    .io_pp_7 (_ppGen_io_pp_7)
  );
  Compressor4to2Array comp42 (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:75:22
    .io_a     (row0S1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:58:25
    .io_b     (row1S1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:59:25
    .io_c     (row2S1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:60:25
    .io_d     (row3S1),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:61:25
    .io_sum   (_comp42_io_sum),
    .io_carry (_comp42_io_carry)
  );
  assign io_product = productS2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :85:26
  assign io_validOut = validS2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mult16Booth2Stage.scala:15:7, :86:26
endmodule

module mac16(	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
  input  clk,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21
         rst_n,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:11:21
         mode,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:12:21
         inA,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:13:21
         inB,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:14:21
  output sum_out,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:15:21
         carry,	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:16:21
         out_ready	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:17:21
);

  wire [31:0] _mult_io_product;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:56:22
  wire        _mult_io_validOut;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:56:22
  wire        _GEN = ~rst_n;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27
  reg  [2:0]  state;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:32:24
  reg  [4:0]  cnt;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24
  reg  [15:0] shiftA;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25
  reg  [15:0] shiftB;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25
  reg  [23:0] accum;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25
  reg  [23:0] prevProduct;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:30
  reg  [23:0] outShiftReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30
  reg         carryReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:41:27
  reg         firstOp;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:42:27
  reg         modeR;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:43:27
  reg         multValidIn;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:45:31
  reg  [31:0] multReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31
  reg         outReadyReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:49:30
  reg         sumOutReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:50:30
  wire        multEnable = state == 3'h1 | state == 3'h2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :53:{29,45,54}
  always @(posedge clk or posedge _GEN) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21, :21:27
    if (_GEN) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21, :21:27
      state <= 3'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
      cnt <= 5'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24
      shiftA <= 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25
      shiftB <= 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25, :36:25
      accum <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25
      prevProduct <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :38:30
      outShiftReg <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :39:30
      carryReg <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :41:27
      firstOp <= 1'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:42:27
      modeR <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :43:27
      multValidIn <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :45:31
      multReg <= 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31
      outReadyReg <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :49:30
      sumOutReg <= 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :50:30
    end
    else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:10:21
      automatic logic [24:0]     addResult;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:64:29, :65:17, :67:17
      automatic logic            _GEN_0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:70:18
      automatic logic [23:0]     macResult;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:70:42, :71:17, :73:17
      automatic logic            _GEN_1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
      automatic logic            _GEN_2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:92:18
      automatic logic            _GEN_3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
      automatic logic            _GEN_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
      automatic logic            _GEN_5;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
      automatic logic            _GEN_6;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
      automatic logic            _GEN_7;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:17, :80:19, :83:21
      automatic logic            _GEN_8;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:140:18
      automatic logic            _GEN_9;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:32:24, :80:19, :140:42, :143:18
      automatic logic [7:0][4:0] _GEN_10;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :78:17, :80:19, :92:41, :131:13, :140:42
      addResult =
        modeR
          ? {1'h0, multReg[23:0]} + {1'h0, accum}
          : {1'h0, multReg[23:0]} + {1'h0, prevProduct};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :37:25, :38:30, :43:27, :46:31, :64:29, :65:{17,41,50}, :67:{17,41,50}
      _GEN_0 = firstOp & ~modeR;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:42:27, :43:27, :64:16, :70:18
      macResult = _GEN_0 ? multReg[23:0] : addResult[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31, :64:29, :65:17, :67:17, :70:{18,42}, :71:{17,27}, :73:{17,29}
      _GEN_1 = state == 3'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :80:19
      _GEN_2 = cnt == 5'hF;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :92:18
      _GEN_3 = state == 3'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :80:19
      _GEN_4 = state == 3'h2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :80:19
      _GEN_5 = state == 3'h3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :80:19
      _GEN_6 = state == 3'h4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :80:19
      _GEN_7 = _GEN_1 | _GEN_3 | _GEN_4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:17, :80:19, :83:21
      _GEN_8 = cnt == 5'h16;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :140:18
      _GEN_9 = _GEN_6 & _GEN_8;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:32:24, :80:19, :140:{18,42}, :143:18
      if (_GEN_1) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
        if (_GEN_2)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:92:18
          state <= 3'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
        shiftA <= {shiftA[14:0], inA};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25, :87:{29,36}
        shiftB <= {shiftB[14:0], inB};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:36:25, :88:{29,36}
        modeR <= mode;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:43:27
        multValidIn <= _GEN_2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:45:31, :92:18
      end
      else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
        if (_GEN_3)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
          state <= 3'h2;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
        else if (_GEN_4) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
          if (_mult_io_validOut)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:56:22
            state <= 3'h3;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
        end
        else if (_GEN_5)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
          state <= 3'h4;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
        else if (_GEN_9)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:32:24, :80:19, :140:42, :143:18
          state <= 3'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
        multValidIn <= ~_GEN_3 & multValidIn;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:45:31, :80:19, :103:21
      end
      _GEN_10 =
        {{cnt},
         {cnt},
         {cnt},
         {_GEN_8 ? 5'h0 : cnt + 5'h1},
         {5'h0},
         {cnt},
         {cnt},
         {_GEN_2 ? 5'h0 : cnt + 5'h1}};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24, :78:17, :80:19, :92:{18,41}, :94:23, :98:{15,22}, :131:13, :140:{18,42}, :141:18, :153:{15,22}
      cnt <= _GEN_10[state];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:32:24, :33:24, :78:17, :80:19, :92:41, :131:13, :140:42
      if (~_GEN_7) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:78:17, :80:19, :83:21
        automatic logic _GEN_11;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :146:{21,32}, :147:19
        _GEN_11 = mode == modeR;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :43:27, :146:{21,32}, :147:19
        if (_GEN_5) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
          if (modeR) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:43:27
            if (_GEN_0)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:70:18
              accum <= multReg[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :46:31, :71:27
            else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:70:18
              accum <= addResult[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :64:29, :65:17, :67:17, :73:29
          end
          else if (_GEN_0)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:70:18
            prevProduct <= multReg[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:30, :46:31, :71:27
          else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:70:18
            prevProduct <= addResult[23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:30, :64:29, :65:17, :67:17, :73:29
          outShiftReg <= macResult;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :70:42, :71:17, :73:17
          carryReg <= (~firstOp | modeR) & addResult[24] | carryReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:41:27, :42:27, :43:27, :64:29, :65:17, :67:17, :124:{15,24,34,46,60}, :125:20
        end
        else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
          automatic logic _GEN_12;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :80:19, :140:42, :146:32
          _GEN_12 = ~_GEN_9 | _GEN_11;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:32:24, :37:25, :80:19, :140:42, :143:18, :146:{21,32}, :147:19
          if (_GEN_12) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :38:30, :80:19, :140:42, :146:32
          end
          else begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:38:30, :80:19, :140:42, :146:32
            accum <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25
            prevProduct <= 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :38:30
          end
          if (_GEN_6)	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:80:19
            outShiftReg <= {outShiftReg[22:0], 1'h0};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :39:30, :138:{27,39}
          carryReg <= _GEN_12 & carryReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :41:27, :80:19, :140:42, :146:32
        end
        firstOp <= ~_GEN_5 & (_GEN_9 & ~_GEN_11 | firstOp);	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:32:24, :37:25, :42:27, :80:19, :128:18, :140:42, :143:18, :146:{21,32}, :147:19, :150:21
      end
      if (_GEN_1 | _GEN_3 | ~(_GEN_4 & _mult_io_validOut)) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31, :56:22, :80:19, :109:32, :110:19
      end
      else	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31, :80:19
        multReg <= _mult_io_product;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31, :56:22
      outReadyReg <= ~_GEN_7 & (_GEN_5 | _GEN_6 & ~_GEN_8);	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :42:27, :49:30, :77:17, :78:17, :80:19, :82:21, :83:21, :129:21, :136:21, :140:{18,42}, :142:23
      sumOutReg <= ~_GEN_7 & (_GEN_5 ? macResult[23] : _GEN_6 & outShiftReg[22]);	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:39:30, :50:30, :70:42, :71:17, :73:17, :78:17, :80:19, :83:21, :130:{21,33}, :137:{21,35}
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
    `ifdef FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `FIRRTL_BEFORE_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      automatic logic [31:0] _RANDOM[0:4];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `ifdef INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        `INIT_RANDOM_PROLOG_	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        end	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
        state = _RANDOM[3'h0][2:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
        cnt = _RANDOM[3'h0][7:3];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :33:24
        shiftA = _RANDOM[3'h0][23:8];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :35:25
        shiftB = {_RANDOM[3'h0][31:24], _RANDOM[3'h1][7:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24, :36:25
        accum = _RANDOM[3'h1][31:8];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :36:25, :37:25
        prevProduct = _RANDOM[3'h2][23:0];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :38:30
        outShiftReg = {_RANDOM[3'h2][31:24], _RANDOM[3'h3][15:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :38:30, :39:30
        carryReg = _RANDOM[3'h3][16];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :41:27
        firstOp = _RANDOM[3'h3][17];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :42:27
        modeR = _RANDOM[3'h3][18];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :43:27
        multValidIn = _RANDOM[3'h3][19];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :45:31
        multReg = {_RANDOM[3'h3][31:20], _RANDOM[3'h4][19:0]};	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :39:30, :46:31
        outReadyReg = _RANDOM[3'h4][20];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :46:31, :49:30
        sumOutReg = _RANDOM[3'h4][21];	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :46:31, :50:30
      `endif // RANDOMIZE_REG_INIT
      if (_GEN) begin	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :21:27
        state = 3'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :32:24
        cnt = 5'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:33:24
        shiftA = 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25
        shiftB = 16'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25, :36:25
        accum = 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25
        prevProduct = 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :38:30
        outShiftReg = 24'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:37:25, :39:30
        carryReg = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :41:27
        firstOp = 1'h1;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:42:27
        modeR = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :43:27
        multValidIn = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :45:31
        multReg = 32'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:46:31
        outReadyReg = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :49:30
        sumOutReg = 1'h0;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27, :50:30
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
      `FIRRTL_AFTER_INITIAL	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Mult16Booth2Stage mult (	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:56:22
    .clock       (clk),
    .reset       (_GEN),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:21:27
    .io_a        (multEnable ? shiftA : 16'h0),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25, :53:45, :57:27
    .io_b        (multEnable ? shiftB : 16'h0),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:35:25, :36:25, :53:45, :58:27
    .io_validIn  (multValidIn),	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:45:31
    .io_product  (_mult_io_product),
    .io_validOut (_mult_io_validOut)
  );
  assign sum_out = sumOutReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :50:30
  assign carry = carryReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :41:27
  assign out_ready = outReadyReg;	// Volumes/disk/work/ysyx/mac/chisel/src/main/scala/mac16/exp_d/Mac16.scala:9:7, :49:30
endmodule

