// Generated by CIRCT firtool-1.62.0
module BoothEncoder(
  input  [15:0] io_b,
  output [7:0]  io_neg,
                io_zero,
                io_two
);

  assign io_neg =
    {io_b[15], io_b[13], io_b[11], io_b[9], io_b[7], io_b[5], io_b[3], io_b[1]};
  assign io_zero =
    {io_b[15:13] == 3'h0 | (&(io_b[15:13])),
     io_b[13:11] == 3'h0 | (&(io_b[13:11])),
     io_b[11:9] == 3'h0 | (&(io_b[11:9])),
     io_b[9:7] == 3'h0 | (&(io_b[9:7])),
     io_b[7:5] == 3'h0 | (&(io_b[7:5])),
     io_b[5:3] == 3'h0 | (&(io_b[5:3])),
     io_b[3:1] == 3'h0 | (&(io_b[3:1])),
     io_b[1:0] == 2'h0};
  assign io_two =
    {io_b[15:13] == 3'h3 | io_b[15:13] == 3'h4,
     io_b[13:11] == 3'h3 | io_b[13:11] == 3'h4,
     io_b[11:9] == 3'h3 | io_b[11:9] == 3'h4,
     io_b[9:7] == 3'h3 | io_b[9:7] == 3'h4,
     io_b[7:5] == 3'h3 | io_b[7:5] == 3'h4,
     io_b[5:3] == 3'h3 | io_b[5:3] == 3'h4,
     io_b[3:1] == 3'h3 | io_b[3:1] == 3'h4,
     io_b[1:0] == 2'h2};
endmodule

module PartialProductGen(
  input  [15:0] io_a,
  input  [7:0]  io_neg,
                io_zero,
                io_two,
  output [32:0] io_pp_0,
                io_pp_1,
                io_pp_2,
                io_pp_3,
                io_pp_4,
                io_pp_5,
                io_pp_6,
                io_pp_7
);

  wire [16:0] _GEN = {io_a, 1'h0};
  wire [16:0] _GEN_0 = {io_a[15], io_a};
  wire [16:0] _GEN_1 = io_two[0] ? _GEN : _GEN_0;
  wire [17:0] io_pp_0_aFinal =
    io_zero[0] ? 18'h0 : io_neg[0] ? 18'h0 - {io_a[15], _GEN_1} : {io_a[15], _GEN_1};
  wire [16:0] _GEN_2 = io_two[1] ? _GEN : _GEN_0;
  wire [17:0] io_pp_1_aFinal =
    io_zero[1] ? 18'h0 : io_neg[1] ? 18'h0 - {io_a[15], _GEN_2} : {io_a[15], _GEN_2};
  wire [16:0] _GEN_3 = io_two[2] ? _GEN : _GEN_0;
  wire [17:0] io_pp_2_aFinal =
    io_zero[2] ? 18'h0 : io_neg[2] ? 18'h0 - {io_a[15], _GEN_3} : {io_a[15], _GEN_3};
  wire [16:0] _GEN_4 = io_two[3] ? _GEN : _GEN_0;
  wire [17:0] io_pp_3_aFinal =
    io_zero[3] ? 18'h0 : io_neg[3] ? 18'h0 - {io_a[15], _GEN_4} : {io_a[15], _GEN_4};
  wire [16:0] _GEN_5 = io_two[4] ? _GEN : _GEN_0;
  wire [17:0] io_pp_4_aFinal =
    io_zero[4] ? 18'h0 : io_neg[4] ? 18'h0 - {io_a[15], _GEN_5} : {io_a[15], _GEN_5};
  wire [16:0] _GEN_6 = io_two[5] ? _GEN : _GEN_0;
  wire [17:0] io_pp_5_aFinal =
    io_zero[5] ? 18'h0 : io_neg[5] ? 18'h0 - {io_a[15], _GEN_6} : {io_a[15], _GEN_6};
  wire [16:0] _GEN_7 = io_two[6] ? _GEN : _GEN_0;
  wire [17:0] io_pp_6_aFinal =
    io_zero[6] ? 18'h0 : io_neg[6] ? 18'h0 - {io_a[15], _GEN_7} : {io_a[15], _GEN_7};
  wire [16:0] _GEN_8 = io_two[7] ? _GEN : _GEN_0;
  wire [17:0] io_pp_7_aFinal =
    io_zero[7] ? 18'h0 : io_neg[7] ? 18'h0 - {io_a[15], _GEN_8} : {io_a[15], _GEN_8};
  assign io_pp_0 = {{15{io_pp_0_aFinal[17]}}, io_pp_0_aFinal};
  assign io_pp_1 = {{15{io_pp_1_aFinal[17]}}, io_pp_1_aFinal};
  assign io_pp_2 = {{15{io_pp_2_aFinal[17]}}, io_pp_2_aFinal};
  assign io_pp_3 = {{15{io_pp_3_aFinal[17]}}, io_pp_3_aFinal};
  assign io_pp_4 = {{15{io_pp_4_aFinal[17]}}, io_pp_4_aFinal};
  assign io_pp_5 = {{15{io_pp_5_aFinal[17]}}, io_pp_5_aFinal};
  assign io_pp_6 = {{15{io_pp_6_aFinal[17]}}, io_pp_6_aFinal};
  assign io_pp_7 = {{15{io_pp_7_aFinal[17]}}, io_pp_7_aFinal};
endmodule

module Compressor4to2(
  input  io_a,
         io_b,
         io_c,
         io_d,
         io_cin,
  output io_sum,
         io_carry,
         io_cout
);

  wire w1 = io_a ^ io_b;
  wire w3 = w1 ^ io_c ^ io_d;
  assign io_sum = w3 ^ io_cin;
  assign io_carry = w3 ? io_cin : io_d;
  assign io_cout = w1 ? io_c : io_a;
endmodule

module Compressor4to2Array(
  input  [39:0] io_a,
                io_b,
                io_c,
                io_d,
  output [39:0] io_sum,
                io_carry
);

  wire _comp_39_io_sum;
  wire _comp_39_io_carry;
  wire _comp_38_io_sum;
  wire _comp_38_io_carry;
  wire _comp_38_io_cout;
  wire _comp_37_io_sum;
  wire _comp_37_io_carry;
  wire _comp_37_io_cout;
  wire _comp_36_io_sum;
  wire _comp_36_io_carry;
  wire _comp_36_io_cout;
  wire _comp_35_io_sum;
  wire _comp_35_io_carry;
  wire _comp_35_io_cout;
  wire _comp_34_io_sum;
  wire _comp_34_io_carry;
  wire _comp_34_io_cout;
  wire _comp_33_io_sum;
  wire _comp_33_io_carry;
  wire _comp_33_io_cout;
  wire _comp_32_io_sum;
  wire _comp_32_io_carry;
  wire _comp_32_io_cout;
  wire _comp_31_io_sum;
  wire _comp_31_io_carry;
  wire _comp_31_io_cout;
  wire _comp_30_io_sum;
  wire _comp_30_io_carry;
  wire _comp_30_io_cout;
  wire _comp_29_io_sum;
  wire _comp_29_io_carry;
  wire _comp_29_io_cout;
  wire _comp_28_io_sum;
  wire _comp_28_io_carry;
  wire _comp_28_io_cout;
  wire _comp_27_io_sum;
  wire _comp_27_io_carry;
  wire _comp_27_io_cout;
  wire _comp_26_io_sum;
  wire _comp_26_io_carry;
  wire _comp_26_io_cout;
  wire _comp_25_io_sum;
  wire _comp_25_io_carry;
  wire _comp_25_io_cout;
  wire _comp_24_io_sum;
  wire _comp_24_io_carry;
  wire _comp_24_io_cout;
  wire _comp_23_io_sum;
  wire _comp_23_io_carry;
  wire _comp_23_io_cout;
  wire _comp_22_io_sum;
  wire _comp_22_io_carry;
  wire _comp_22_io_cout;
  wire _comp_21_io_sum;
  wire _comp_21_io_carry;
  wire _comp_21_io_cout;
  wire _comp_20_io_sum;
  wire _comp_20_io_carry;
  wire _comp_20_io_cout;
  wire _comp_19_io_sum;
  wire _comp_19_io_carry;
  wire _comp_19_io_cout;
  wire _comp_18_io_sum;
  wire _comp_18_io_carry;
  wire _comp_18_io_cout;
  wire _comp_17_io_sum;
  wire _comp_17_io_carry;
  wire _comp_17_io_cout;
  wire _comp_16_io_sum;
  wire _comp_16_io_carry;
  wire _comp_16_io_cout;
  wire _comp_15_io_sum;
  wire _comp_15_io_carry;
  wire _comp_15_io_cout;
  wire _comp_14_io_sum;
  wire _comp_14_io_carry;
  wire _comp_14_io_cout;
  wire _comp_13_io_sum;
  wire _comp_13_io_carry;
  wire _comp_13_io_cout;
  wire _comp_12_io_sum;
  wire _comp_12_io_carry;
  wire _comp_12_io_cout;
  wire _comp_11_io_sum;
  wire _comp_11_io_carry;
  wire _comp_11_io_cout;
  wire _comp_10_io_sum;
  wire _comp_10_io_carry;
  wire _comp_10_io_cout;
  wire _comp_9_io_sum;
  wire _comp_9_io_carry;
  wire _comp_9_io_cout;
  wire _comp_8_io_sum;
  wire _comp_8_io_carry;
  wire _comp_8_io_cout;
  wire _comp_7_io_sum;
  wire _comp_7_io_carry;
  wire _comp_7_io_cout;
  wire _comp_6_io_sum;
  wire _comp_6_io_carry;
  wire _comp_6_io_cout;
  wire _comp_5_io_sum;
  wire _comp_5_io_carry;
  wire _comp_5_io_cout;
  wire _comp_4_io_sum;
  wire _comp_4_io_carry;
  wire _comp_4_io_cout;
  wire _comp_3_io_sum;
  wire _comp_3_io_carry;
  wire _comp_3_io_cout;
  wire _comp_2_io_sum;
  wire _comp_2_io_carry;
  wire _comp_2_io_cout;
  wire _comp_1_io_sum;
  wire _comp_1_io_carry;
  wire _comp_1_io_cout;
  wire _comp_io_sum;
  wire _comp_io_carry;
  wire _comp_io_cout;
  Compressor4to2 comp (
    .io_a     (io_a[0]),
    .io_b     (io_b[0]),
    .io_c     (io_c[0]),
    .io_d     (io_d[0]),
    .io_cin   (1'h0),
    .io_sum   (_comp_io_sum),
    .io_carry (_comp_io_carry),
    .io_cout  (_comp_io_cout)
  );
  Compressor4to2 comp_1 (
    .io_a     (io_a[1]),
    .io_b     (io_b[1]),
    .io_c     (io_c[1]),
    .io_d     (io_d[1]),
    .io_cin   (_comp_io_cout),
    .io_sum   (_comp_1_io_sum),
    .io_carry (_comp_1_io_carry),
    .io_cout  (_comp_1_io_cout)
  );
  Compressor4to2 comp_2 (
    .io_a     (io_a[2]),
    .io_b     (io_b[2]),
    .io_c     (io_c[2]),
    .io_d     (io_d[2]),
    .io_cin   (_comp_1_io_cout),
    .io_sum   (_comp_2_io_sum),
    .io_carry (_comp_2_io_carry),
    .io_cout  (_comp_2_io_cout)
  );
  Compressor4to2 comp_3 (
    .io_a     (io_a[3]),
    .io_b     (io_b[3]),
    .io_c     (io_c[3]),
    .io_d     (io_d[3]),
    .io_cin   (_comp_2_io_cout),
    .io_sum   (_comp_3_io_sum),
    .io_carry (_comp_3_io_carry),
    .io_cout  (_comp_3_io_cout)
  );
  Compressor4to2 comp_4 (
    .io_a     (io_a[4]),
    .io_b     (io_b[4]),
    .io_c     (io_c[4]),
    .io_d     (io_d[4]),
    .io_cin   (_comp_3_io_cout),
    .io_sum   (_comp_4_io_sum),
    .io_carry (_comp_4_io_carry),
    .io_cout  (_comp_4_io_cout)
  );
  Compressor4to2 comp_5 (
    .io_a     (io_a[5]),
    .io_b     (io_b[5]),
    .io_c     (io_c[5]),
    .io_d     (io_d[5]),
    .io_cin   (_comp_4_io_cout),
    .io_sum   (_comp_5_io_sum),
    .io_carry (_comp_5_io_carry),
    .io_cout  (_comp_5_io_cout)
  );
  Compressor4to2 comp_6 (
    .io_a     (io_a[6]),
    .io_b     (io_b[6]),
    .io_c     (io_c[6]),
    .io_d     (io_d[6]),
    .io_cin   (_comp_5_io_cout),
    .io_sum   (_comp_6_io_sum),
    .io_carry (_comp_6_io_carry),
    .io_cout  (_comp_6_io_cout)
  );
  Compressor4to2 comp_7 (
    .io_a     (io_a[7]),
    .io_b     (io_b[7]),
    .io_c     (io_c[7]),
    .io_d     (io_d[7]),
    .io_cin   (_comp_6_io_cout),
    .io_sum   (_comp_7_io_sum),
    .io_carry (_comp_7_io_carry),
    .io_cout  (_comp_7_io_cout)
  );
  Compressor4to2 comp_8 (
    .io_a     (io_a[8]),
    .io_b     (io_b[8]),
    .io_c     (io_c[8]),
    .io_d     (io_d[8]),
    .io_cin   (_comp_7_io_cout),
    .io_sum   (_comp_8_io_sum),
    .io_carry (_comp_8_io_carry),
    .io_cout  (_comp_8_io_cout)
  );
  Compressor4to2 comp_9 (
    .io_a     (io_a[9]),
    .io_b     (io_b[9]),
    .io_c     (io_c[9]),
    .io_d     (io_d[9]),
    .io_cin   (_comp_8_io_cout),
    .io_sum   (_comp_9_io_sum),
    .io_carry (_comp_9_io_carry),
    .io_cout  (_comp_9_io_cout)
  );
  Compressor4to2 comp_10 (
    .io_a     (io_a[10]),
    .io_b     (io_b[10]),
    .io_c     (io_c[10]),
    .io_d     (io_d[10]),
    .io_cin   (_comp_9_io_cout),
    .io_sum   (_comp_10_io_sum),
    .io_carry (_comp_10_io_carry),
    .io_cout  (_comp_10_io_cout)
  );
  Compressor4to2 comp_11 (
    .io_a     (io_a[11]),
    .io_b     (io_b[11]),
    .io_c     (io_c[11]),
    .io_d     (io_d[11]),
    .io_cin   (_comp_10_io_cout),
    .io_sum   (_comp_11_io_sum),
    .io_carry (_comp_11_io_carry),
    .io_cout  (_comp_11_io_cout)
  );
  Compressor4to2 comp_12 (
    .io_a     (io_a[12]),
    .io_b     (io_b[12]),
    .io_c     (io_c[12]),
    .io_d     (io_d[12]),
    .io_cin   (_comp_11_io_cout),
    .io_sum   (_comp_12_io_sum),
    .io_carry (_comp_12_io_carry),
    .io_cout  (_comp_12_io_cout)
  );
  Compressor4to2 comp_13 (
    .io_a     (io_a[13]),
    .io_b     (io_b[13]),
    .io_c     (io_c[13]),
    .io_d     (io_d[13]),
    .io_cin   (_comp_12_io_cout),
    .io_sum   (_comp_13_io_sum),
    .io_carry (_comp_13_io_carry),
    .io_cout  (_comp_13_io_cout)
  );
  Compressor4to2 comp_14 (
    .io_a     (io_a[14]),
    .io_b     (io_b[14]),
    .io_c     (io_c[14]),
    .io_d     (io_d[14]),
    .io_cin   (_comp_13_io_cout),
    .io_sum   (_comp_14_io_sum),
    .io_carry (_comp_14_io_carry),
    .io_cout  (_comp_14_io_cout)
  );
  Compressor4to2 comp_15 (
    .io_a     (io_a[15]),
    .io_b     (io_b[15]),
    .io_c     (io_c[15]),
    .io_d     (io_d[15]),
    .io_cin   (_comp_14_io_cout),
    .io_sum   (_comp_15_io_sum),
    .io_carry (_comp_15_io_carry),
    .io_cout  (_comp_15_io_cout)
  );
  Compressor4to2 comp_16 (
    .io_a     (io_a[16]),
    .io_b     (io_b[16]),
    .io_c     (io_c[16]),
    .io_d     (io_d[16]),
    .io_cin   (_comp_15_io_cout),
    .io_sum   (_comp_16_io_sum),
    .io_carry (_comp_16_io_carry),
    .io_cout  (_comp_16_io_cout)
  );
  Compressor4to2 comp_17 (
    .io_a     (io_a[17]),
    .io_b     (io_b[17]),
    .io_c     (io_c[17]),
    .io_d     (io_d[17]),
    .io_cin   (_comp_16_io_cout),
    .io_sum   (_comp_17_io_sum),
    .io_carry (_comp_17_io_carry),
    .io_cout  (_comp_17_io_cout)
  );
  Compressor4to2 comp_18 (
    .io_a     (io_a[18]),
    .io_b     (io_b[18]),
    .io_c     (io_c[18]),
    .io_d     (io_d[18]),
    .io_cin   (_comp_17_io_cout),
    .io_sum   (_comp_18_io_sum),
    .io_carry (_comp_18_io_carry),
    .io_cout  (_comp_18_io_cout)
  );
  Compressor4to2 comp_19 (
    .io_a     (io_a[19]),
    .io_b     (io_b[19]),
    .io_c     (io_c[19]),
    .io_d     (io_d[19]),
    .io_cin   (_comp_18_io_cout),
    .io_sum   (_comp_19_io_sum),
    .io_carry (_comp_19_io_carry),
    .io_cout  (_comp_19_io_cout)
  );
  Compressor4to2 comp_20 (
    .io_a     (io_a[20]),
    .io_b     (io_b[20]),
    .io_c     (io_c[20]),
    .io_d     (io_d[20]),
    .io_cin   (_comp_19_io_cout),
    .io_sum   (_comp_20_io_sum),
    .io_carry (_comp_20_io_carry),
    .io_cout  (_comp_20_io_cout)
  );
  Compressor4to2 comp_21 (
    .io_a     (io_a[21]),
    .io_b     (io_b[21]),
    .io_c     (io_c[21]),
    .io_d     (io_d[21]),
    .io_cin   (_comp_20_io_cout),
    .io_sum   (_comp_21_io_sum),
    .io_carry (_comp_21_io_carry),
    .io_cout  (_comp_21_io_cout)
  );
  Compressor4to2 comp_22 (
    .io_a     (io_a[22]),
    .io_b     (io_b[22]),
    .io_c     (io_c[22]),
    .io_d     (io_d[22]),
    .io_cin   (_comp_21_io_cout),
    .io_sum   (_comp_22_io_sum),
    .io_carry (_comp_22_io_carry),
    .io_cout  (_comp_22_io_cout)
  );
  Compressor4to2 comp_23 (
    .io_a     (io_a[23]),
    .io_b     (io_b[23]),
    .io_c     (io_c[23]),
    .io_d     (io_d[23]),
    .io_cin   (_comp_22_io_cout),
    .io_sum   (_comp_23_io_sum),
    .io_carry (_comp_23_io_carry),
    .io_cout  (_comp_23_io_cout)
  );
  Compressor4to2 comp_24 (
    .io_a     (io_a[24]),
    .io_b     (io_b[24]),
    .io_c     (io_c[24]),
    .io_d     (io_d[24]),
    .io_cin   (_comp_23_io_cout),
    .io_sum   (_comp_24_io_sum),
    .io_carry (_comp_24_io_carry),
    .io_cout  (_comp_24_io_cout)
  );
  Compressor4to2 comp_25 (
    .io_a     (io_a[25]),
    .io_b     (io_b[25]),
    .io_c     (io_c[25]),
    .io_d     (io_d[25]),
    .io_cin   (_comp_24_io_cout),
    .io_sum   (_comp_25_io_sum),
    .io_carry (_comp_25_io_carry),
    .io_cout  (_comp_25_io_cout)
  );
  Compressor4to2 comp_26 (
    .io_a     (io_a[26]),
    .io_b     (io_b[26]),
    .io_c     (io_c[26]),
    .io_d     (io_d[26]),
    .io_cin   (_comp_25_io_cout),
    .io_sum   (_comp_26_io_sum),
    .io_carry (_comp_26_io_carry),
    .io_cout  (_comp_26_io_cout)
  );
  Compressor4to2 comp_27 (
    .io_a     (io_a[27]),
    .io_b     (io_b[27]),
    .io_c     (io_c[27]),
    .io_d     (io_d[27]),
    .io_cin   (_comp_26_io_cout),
    .io_sum   (_comp_27_io_sum),
    .io_carry (_comp_27_io_carry),
    .io_cout  (_comp_27_io_cout)
  );
  Compressor4to2 comp_28 (
    .io_a     (io_a[28]),
    .io_b     (io_b[28]),
    .io_c     (io_c[28]),
    .io_d     (io_d[28]),
    .io_cin   (_comp_27_io_cout),
    .io_sum   (_comp_28_io_sum),
    .io_carry (_comp_28_io_carry),
    .io_cout  (_comp_28_io_cout)
  );
  Compressor4to2 comp_29 (
    .io_a     (io_a[29]),
    .io_b     (io_b[29]),
    .io_c     (io_c[29]),
    .io_d     (io_d[29]),
    .io_cin   (_comp_28_io_cout),
    .io_sum   (_comp_29_io_sum),
    .io_carry (_comp_29_io_carry),
    .io_cout  (_comp_29_io_cout)
  );
  Compressor4to2 comp_30 (
    .io_a     (io_a[30]),
    .io_b     (io_b[30]),
    .io_c     (io_c[30]),
    .io_d     (io_d[30]),
    .io_cin   (_comp_29_io_cout),
    .io_sum   (_comp_30_io_sum),
    .io_carry (_comp_30_io_carry),
    .io_cout  (_comp_30_io_cout)
  );
  Compressor4to2 comp_31 (
    .io_a     (io_a[31]),
    .io_b     (io_b[31]),
    .io_c     (io_c[31]),
    .io_d     (io_d[31]),
    .io_cin   (_comp_30_io_cout),
    .io_sum   (_comp_31_io_sum),
    .io_carry (_comp_31_io_carry),
    .io_cout  (_comp_31_io_cout)
  );
  Compressor4to2 comp_32 (
    .io_a     (io_a[32]),
    .io_b     (io_b[32]),
    .io_c     (io_c[32]),
    .io_d     (io_d[32]),
    .io_cin   (_comp_31_io_cout),
    .io_sum   (_comp_32_io_sum),
    .io_carry (_comp_32_io_carry),
    .io_cout  (_comp_32_io_cout)
  );
  Compressor4to2 comp_33 (
    .io_a     (io_a[33]),
    .io_b     (io_b[33]),
    .io_c     (io_c[33]),
    .io_d     (io_d[33]),
    .io_cin   (_comp_32_io_cout),
    .io_sum   (_comp_33_io_sum),
    .io_carry (_comp_33_io_carry),
    .io_cout  (_comp_33_io_cout)
  );
  Compressor4to2 comp_34 (
    .io_a     (io_a[34]),
    .io_b     (io_b[34]),
    .io_c     (io_c[34]),
    .io_d     (io_d[34]),
    .io_cin   (_comp_33_io_cout),
    .io_sum   (_comp_34_io_sum),
    .io_carry (_comp_34_io_carry),
    .io_cout  (_comp_34_io_cout)
  );
  Compressor4to2 comp_35 (
    .io_a     (io_a[35]),
    .io_b     (io_b[35]),
    .io_c     (io_c[35]),
    .io_d     (io_d[35]),
    .io_cin   (_comp_34_io_cout),
    .io_sum   (_comp_35_io_sum),
    .io_carry (_comp_35_io_carry),
    .io_cout  (_comp_35_io_cout)
  );
  Compressor4to2 comp_36 (
    .io_a     (io_a[36]),
    .io_b     (io_b[36]),
    .io_c     (io_c[36]),
    .io_d     (io_d[36]),
    .io_cin   (_comp_35_io_cout),
    .io_sum   (_comp_36_io_sum),
    .io_carry (_comp_36_io_carry),
    .io_cout  (_comp_36_io_cout)
  );
  Compressor4to2 comp_37 (
    .io_a     (io_a[37]),
    .io_b     (io_b[37]),
    .io_c     (io_c[37]),
    .io_d     (io_d[37]),
    .io_cin   (_comp_36_io_cout),
    .io_sum   (_comp_37_io_sum),
    .io_carry (_comp_37_io_carry),
    .io_cout  (_comp_37_io_cout)
  );
  Compressor4to2 comp_38 (
    .io_a     (io_a[38]),
    .io_b     (io_b[38]),
    .io_c     (io_c[38]),
    .io_d     (io_d[38]),
    .io_cin   (_comp_37_io_cout),
    .io_sum   (_comp_38_io_sum),
    .io_carry (_comp_38_io_carry),
    .io_cout  (_comp_38_io_cout)
  );
  Compressor4to2 comp_39 (
    .io_a     (io_a[39]),
    .io_b     (io_b[39]),
    .io_c     (io_c[39]),
    .io_d     (io_d[39]),
    .io_cin   (_comp_38_io_cout),
    .io_sum   (_comp_39_io_sum),
    .io_carry (_comp_39_io_carry),
    .io_cout  (/* unused */)
  );
  assign io_sum =
    {_comp_39_io_sum,
     _comp_38_io_sum,
     _comp_37_io_sum,
     _comp_36_io_sum,
     _comp_35_io_sum,
     _comp_34_io_sum,
     _comp_33_io_sum,
     _comp_32_io_sum,
     _comp_31_io_sum,
     _comp_30_io_sum,
     _comp_29_io_sum,
     _comp_28_io_sum,
     _comp_27_io_sum,
     _comp_26_io_sum,
     _comp_25_io_sum,
     _comp_24_io_sum,
     _comp_23_io_sum,
     _comp_22_io_sum,
     _comp_21_io_sum,
     _comp_20_io_sum,
     _comp_19_io_sum,
     _comp_18_io_sum,
     _comp_17_io_sum,
     _comp_16_io_sum,
     _comp_15_io_sum,
     _comp_14_io_sum,
     _comp_13_io_sum,
     _comp_12_io_sum,
     _comp_11_io_sum,
     _comp_10_io_sum,
     _comp_9_io_sum,
     _comp_8_io_sum,
     _comp_7_io_sum,
     _comp_6_io_sum,
     _comp_5_io_sum,
     _comp_4_io_sum,
     _comp_3_io_sum,
     _comp_2_io_sum,
     _comp_1_io_sum,
     _comp_io_sum};
  assign io_carry =
    {_comp_39_io_carry,
     _comp_38_io_carry,
     _comp_37_io_carry,
     _comp_36_io_carry,
     _comp_35_io_carry,
     _comp_34_io_carry,
     _comp_33_io_carry,
     _comp_32_io_carry,
     _comp_31_io_carry,
     _comp_30_io_carry,
     _comp_29_io_carry,
     _comp_28_io_carry,
     _comp_27_io_carry,
     _comp_26_io_carry,
     _comp_25_io_carry,
     _comp_24_io_carry,
     _comp_23_io_carry,
     _comp_22_io_carry,
     _comp_21_io_carry,
     _comp_20_io_carry,
     _comp_19_io_carry,
     _comp_18_io_carry,
     _comp_17_io_carry,
     _comp_16_io_carry,
     _comp_15_io_carry,
     _comp_14_io_carry,
     _comp_13_io_carry,
     _comp_12_io_carry,
     _comp_11_io_carry,
     _comp_10_io_carry,
     _comp_9_io_carry,
     _comp_8_io_carry,
     _comp_7_io_carry,
     _comp_6_io_carry,
     _comp_5_io_carry,
     _comp_4_io_carry,
     _comp_3_io_carry,
     _comp_2_io_carry,
     _comp_1_io_carry,
     _comp_io_carry};
endmodule

module Mult16BoothGated(
  input         clock,
                reset,
  input  [15:0] io_a,
                io_b,
  input         io_validIn,
  output [31:0] io_product,
  output        io_validOut
);

  wire [39:0] _comp42_io_sum;
  wire [39:0] _comp42_io_carry;
  wire [32:0] _ppGen_io_pp_0;
  wire [32:0] _ppGen_io_pp_1;
  wire [32:0] _ppGen_io_pp_2;
  wire [32:0] _ppGen_io_pp_3;
  wire [32:0] _ppGen_io_pp_4;
  wire [32:0] _ppGen_io_pp_5;
  wire [32:0] _ppGen_io_pp_6;
  wire [32:0] _ppGen_io_pp_7;
  wire [7:0]  _booth_io_neg;
  wire [7:0]  _booth_io_zero;
  wire [7:0]  _booth_io_two;
  reg  [7:0]  negS1;
  reg  [7:0]  zeroS1;
  reg  [7:0]  twoS1;
  reg  [15:0] aS1;
  reg         validS1;
  reg  [39:0] row0S2;
  reg  [39:0] row1S2;
  reg  [39:0] row2S2;
  reg  [39:0] row3S2;
  reg         validS2;
  reg  [31:0] productS3;
  reg         validS3;
  wire [39:0] csa1Sum =
    {{7{_ppGen_io_pp_0[32]}}, _ppGen_io_pp_0}
    ^ {{5{_ppGen_io_pp_1[32]}}, _ppGen_io_pp_1, 2'h0}
    ^ {{3{_ppGen_io_pp_2[32]}}, _ppGen_io_pp_2, 4'h0};
  wire [38:0] _GEN = {{6{_ppGen_io_pp_0[32]}}, _ppGen_io_pp_0};
  wire [38:0] _GEN_0 = {{4{_ppGen_io_pp_1[32]}}, _ppGen_io_pp_1, 2'h0};
  wire [38:0] _GEN_1 = {{2{_ppGen_io_pp_2[32]}}, _ppGen_io_pp_2, 4'h0};
  wire [38:0] csa1Carry = _GEN & _GEN_0 | _GEN_0 & _GEN_1 | _GEN & _GEN_1;
  wire [39:0] csa2Sum =
    {_ppGen_io_pp_3[32], _ppGen_io_pp_3, 6'h0} ^ {1'h0, _ppGen_io_pp_4[30:0], 8'h0}
    ^ {1'h0, _ppGen_io_pp_5[28:0], 10'h0};
  wire [38:0] _GEN_2 = {_ppGen_io_pp_3, 6'h0};
  wire [38:0] _GEN_3 = {_ppGen_io_pp_4[30:0], 8'h0};
  wire [38:0] _GEN_4 = {_ppGen_io_pp_5[28:0], 10'h0};
  wire [38:0] csa2Carry = _GEN_2 & _GEN_3 | _GEN_3 & _GEN_4 | _GEN_2 & _GEN_4;
  wire [38:0] _GEN_5 = {csa1Carry[37:0], 1'h0};
  wire [38:0] _GEN_6 = {_ppGen_io_pp_6[26:0], 12'h0};
  wire [38:0] _GEN_7 = {csa2Carry[37:0], 1'h0};
  wire [38:0] _GEN_8 = {_ppGen_io_pp_7[24:0], 14'h0};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      negS1 <= 8'h0;
      zeroS1 <= 8'h0;
      twoS1 <= 8'h0;
      aS1 <= 16'h0;
      validS1 <= 1'h0;
      row0S2 <= 40'h0;
      row1S2 <= 40'h0;
      row2S2 <= 40'h0;
      row3S2 <= 40'h0;
      validS2 <= 1'h0;
      productS3 <= 32'h0;
      validS3 <= 1'h0;
    end
    else begin
      if (io_validIn) begin
        negS1 <= _booth_io_neg;
        zeroS1 <= _booth_io_zero;
        twoS1 <= _booth_io_two;
        aS1 <= io_a;
      end
      validS1 <= io_validIn;
      if (validS1) begin
        row0S2 <= csa1Sum ^ {csa1Carry, 1'h0} ^ {1'h0, _ppGen_io_pp_6[26:0], 12'h0};
        row1S2 <=
          {csa1Sum[38:0] & _GEN_5 | _GEN_5 & _GEN_6 | csa1Sum[38:0] & _GEN_6, 1'h0};
        row2S2 <= csa2Sum ^ {csa2Carry, 1'h0} ^ {1'h0, _ppGen_io_pp_7[24:0], 14'h0};
        row3S2 <=
          {csa2Sum[38:0] & _GEN_7 | _GEN_7 & _GEN_8 | csa2Sum[38:0] & _GEN_8, 1'h0};
      end
      validS2 <= validS1;
      if (validS2)
        productS3 <= _comp42_io_sum[31:0] + {_comp42_io_carry[30:0], 1'h0};
      validS3 <= validS2;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        negS1 = 8'h0;
        zeroS1 = 8'h0;
        twoS1 = 8'h0;
        aS1 = 16'h0;
        validS1 = 1'h0;
        row0S2 = 40'h0;
        row1S2 = 40'h0;
        row2S2 = 40'h0;
        row3S2 = 40'h0;
        validS2 = 1'h0;
        productS3 = 32'h0;
        validS3 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  BoothEncoder booth (
    .io_b    (io_b),
    .io_neg  (_booth_io_neg),
    .io_zero (_booth_io_zero),
    .io_two  (_booth_io_two)
  );
  PartialProductGen ppGen (
    .io_a    (aS1),
    .io_neg  (negS1),
    .io_zero (zeroS1),
    .io_two  (twoS1),
    .io_pp_0 (_ppGen_io_pp_0),
    .io_pp_1 (_ppGen_io_pp_1),
    .io_pp_2 (_ppGen_io_pp_2),
    .io_pp_3 (_ppGen_io_pp_3),
    .io_pp_4 (_ppGen_io_pp_4),
    .io_pp_5 (_ppGen_io_pp_5),
    .io_pp_6 (_ppGen_io_pp_6),
    .io_pp_7 (_ppGen_io_pp_7)
  );
  Compressor4to2Array comp42 (
    .io_a     (row0S2),
    .io_b     (row1S2),
    .io_c     (row2S2),
    .io_d     (row3S2),
    .io_sum   (_comp42_io_sum),
    .io_carry (_comp42_io_carry)
  );
  assign io_product = productS3;
  assign io_validOut = validS3;
endmodule

module mac16(
  input  clk,
         rst_n,
         mode,
         inA,
         inB,
  output sum_out,
         carry,
         out_ready
);

  wire [31:0]      _mult_io_product;
  wire             _mult_io_validOut;
  wire             _GEN = ~rst_n;
  reg  [2:0]       state;
  reg  [4:0]       cnt;
  reg  [15:0]      shiftA;
  reg  [15:0]      shiftB;
  reg  [23:0]      accum;
  reg  [23:0]      prevProduct;
  reg  [23:0]      outShiftReg;
  reg              carryReg;
  reg              firstOp;
  reg              modeR;
  reg  [15:0]      multInA;
  reg  [15:0]      multInB;
  reg              multInputValid;
  reg  [31:0]      multReg;
  reg              outReadyReg;
  reg              sumOutReg;
  wire             _GEN_0 = mode == modeR;
  wire [24:0]      addResult =
    modeR
      ? {1'h0, multReg[23:0]} + {1'h0, accum}
      : {1'h0, multReg[23:0]} + {1'h0, prevProduct};
  wire             _GEN_1 = firstOp & ~modeR;
  wire [23:0]      macResult = _GEN_1 ? multReg[23:0] : addResult[23:0];
  wire             _GEN_2 = state == 3'h0;
  wire             _GEN_3 = cnt == 5'hF;
  wire             _GEN_4 = state == 3'h1;
  wire             _GEN_5 = state == 3'h2;
  wire             _GEN_6 = state == 3'h3;
  wire             _GEN_7 = state == 3'h4;
  wire             _GEN_8 = state == 3'h5;
  wire             _GEN_9 = _GEN_2 | _GEN_4 | _GEN_5 | _GEN_6;
  wire             _GEN_10 = cnt == 5'h16;
  wire             _GEN_11 = _GEN_8 & _GEN_10;
  wire [2:0]       _GEN_12 = _GEN_11 ? 3'h0 : state;
  wire             _GEN_13 = _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | ~_GEN_11;
  wire [15:0]      _GEN_14 = _GEN_13 ? shiftA : 16'h0;
  wire [15:0]      _GEN_15 = _GEN_13 ? shiftB : 16'h0;
  wire [7:0][2:0]  _GEN_16 =
    {{_GEN_12},
     {_GEN_12},
     {_GEN_12},
     {3'h5},
     {_mult_io_validOut ? 3'h4 : state},
     {3'h3},
     {3'h2},
     {_GEN_3 ? 3'h1 : state}};
  wire [7:0][4:0]  _GEN_17 =
    {{cnt},
     {cnt},
     {_GEN_10 ? 5'h0 : cnt + 5'h1},
     {5'h0},
     {cnt},
     {cnt},
     {cnt},
     {_GEN_3 ? 5'h0 : cnt + 5'h1}};
  wire [7:0][15:0] _GEN_18 =
    {{_GEN_14},
     {_GEN_14},
     {_GEN_14},
     {shiftA},
     {shiftA},
     {shiftA},
     {shiftA},
     {{shiftA[14:0], inA}}};
  wire [7:0][15:0] _GEN_19 =
    {{_GEN_15},
     {_GEN_15},
     {_GEN_15},
     {shiftB},
     {shiftB},
     {shiftB},
     {shiftB},
     {{shiftB[14:0], inB}}};
  wire             _GEN_20 = ~_GEN_11 | _GEN_0;
  always @(posedge clk or posedge _GEN) begin
    if (_GEN) begin
      state <= 3'h0;
      cnt <= 5'h0;
      shiftA <= 16'h0;
      shiftB <= 16'h0;
      accum <= 24'h0;
      prevProduct <= 24'h0;
      outShiftReg <= 24'h0;
      carryReg <= 1'h0;
      firstOp <= 1'h1;
      modeR <= 1'h0;
      multInA <= 16'h0;
      multInB <= 16'h0;
      multInputValid <= 1'h0;
      multReg <= 32'h0;
      outReadyReg <= 1'h0;
      sumOutReg <= 1'h0;
    end
    else begin
      state <= _GEN_16[state];
      cnt <= _GEN_17[state];
      shiftA <= _GEN_18[state];
      shiftB <= _GEN_19[state];
      if (~_GEN_9) begin
        if (_GEN_7) begin
          if (modeR) begin
            if (_GEN_1)
              accum <= multReg[23:0];
            else
              accum <= addResult[23:0];
          end
          else if (_GEN_1)
            prevProduct <= multReg[23:0];
          else
            prevProduct <= addResult[23:0];
          outShiftReg <= macResult;
          carryReg <= (~firstOp | modeR) & addResult[24] | carryReg;
        end
        else begin
          if (_GEN_20) begin
          end
          else begin
            accum <= 24'h0;
            prevProduct <= 24'h0;
          end
          if (_GEN_8)
            outShiftReg <= {outShiftReg[22:0], 1'h0};
          carryReg <= _GEN_20 & carryReg;
        end
        firstOp <= ~_GEN_7 & (_GEN_11 & ~_GEN_0 | firstOp);
      end
      if (_GEN_2)
        modeR <= mode;
      if (_GEN_2 & _GEN_3) begin
        multInA <= {shiftA[14:0], inA};
        multInB <= {shiftB[14:0], inB};
      end
      multInputValid <= _GEN_2 & _GEN_3;
      if (_GEN_2 | _GEN_4 | _GEN_5 | ~(_GEN_6 & _mult_io_validOut)) begin
      end
      else
        multReg <= _mult_io_product;
      outReadyReg <= ~_GEN_9 & (_GEN_7 | _GEN_8 & ~_GEN_10);
      sumOutReg <= ~_GEN_9 & (_GEN_7 ? macResult[23] : _GEN_8 & outShiftReg[22]);
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (_GEN) begin
        state = 3'h0;
        cnt = 5'h0;
        shiftA = 16'h0;
        shiftB = 16'h0;
        accum = 24'h0;
        prevProduct = 24'h0;
        outShiftReg = 24'h0;
        carryReg = 1'h0;
        firstOp = 1'h1;
        modeR = 1'h0;
        multInA = 16'h0;
        multInB = 16'h0;
        multInputValid = 1'h0;
        multReg = 32'h0;
        outReadyReg = 1'h0;
        sumOutReg = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Mult16BoothGated mult (
    .clock       (clk),
    .reset       (_GEN),
    .io_a        (multInA),
    .io_b        (multInB),
    .io_validIn  (multInputValid),
    .io_product  (_mult_io_product),
    .io_validOut (_mult_io_validOut)
  );
  assign sum_out = sumOutReg;
  assign carry = carryReg;
  assign out_ready = outReadyReg;
endmodule

