#define CONFIG_ISA_riscv 1
#define CONFIG_TRACE 1
#define CONFIG_ITRACE 1
#define CONFIG_MTRACE 1
#define CONFIG_FTRACE 1

#ifdef CONFIG_ITRACE_RINGBUF
#define IRB_LENGTH CONFIG_ITRACE_RINGBUF
#else
#define IRB_LENGTH 32
#endif

#ifdef CONFIG_FTRACE_RINGBUF
#define FRB_LENGTH CONFIG_FTRACE_RINGBUF
#else
#define FRB_LENGTH 32
#endif

#ifdef CONFIG_MTRACE_RINGBUF
#define MRB_LENGTH CONFIG_MTRACE_RINGBUF
#else
#define MRB_LENGTH 32
#endif

#define CONFIG_WATCHPOINT 1
#define CONFIG_DIFFTEST 1 // Compile-time: enable DIFFTEST support
// #define CONFIG_BATCH 1    // Default batch mode

#define CONFIG_MBASE 0x80000000
#define CONFIG_MSIZE 0x40000000
#define CONFIG_PMEM_MALLOC 1
#define CONFIG_PMEM_DPIC 1
#define CONFIG_PC_RESET_OFFSET 0
#define CONFIG_TARGET_NATIVE_ELF 1

#define CONFIG_DEVICE 1
#define CONFIG_RTC_MMIO 0xa0000048
#define CONFIG_SERIAL_MMIO 0xa00003f8

#define CONFIG_TIMER_GETTIMEOFDAY 1

// #define CONFIG_TRACE
#define CONFIG_TRACE_START 0
#define CONFIG_TRACE_MAX 200000 * 2